// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// WithoutDefaultConst.proto

export enum ConstEnum1 {
  DEFAULT = 0,
}

export const ConstEnum1Values = [ConstEnum1.DEFAULT];

export const enum ConstConstEnum1 {
  DEFAULT = 0,
}

export const ConstConstEnum1Values = [ConstConstEnum1.DEFAULT];
