// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// MapValueTest.proto

import * as Webpb from "webpb";

export enum Direction {
  asc = 0,
  desc = 1,
}

export const DirectionValues = [
  Direction.asc,
  Direction.desc,
];

export const enum ConstDirection {
  asc = 0,
  desc = 1,
}

export const ConstDirectionValues = [
  ConstDirection.asc,
  ConstDirection.desc,
];

export interface IMapValueTestPb {
  sort: Record<string, Direction>;
}

export class MapValueTestPb implements IMapValueTestPb, Webpb.WebpbMessage {
  sort!: Record<string, Direction>;
  webpbMeta: () => Webpb.WebpbMeta;

  static CLASS = "MapValueTestPb";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IMapValueTestPb) {
    Webpb.assign(p, this, []);
    this.webpbMeta = () =>
      ({
        class: "MapValueTestPb",
        context: "",
        method: "",
        path: "",
      } as Webpb.WebpbMeta);
  }

  static create(p?: IMapValueTestPb): MapValueTestPb {
    return new MapValueTestPb(p);
  }

  static fromAlias(data?: unknown): MapValueTestPb {
    return MapValueTestPb.create(data as IMapValueTestPb);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
