// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// BadClassOrInterface.proto

import * as Webpb from "webpb";

export interface IBadAnnotation extends ....IBadClassOrInterface {
  foo_2?: number | null;
  bar_2?: string | null;
}

export class BadAnnotation extends ....BadClassOrInterface implements IBadAnnotation, Webpb.WebpbMessage {
  foo_2?: number | null;
  bar_2?: string | null;

  static CLASS = "BadAnnotation";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IBadAnnotation) {
    super();
    Webpb.assign(p, this, []);
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: BadAnnotation.CLASS,
      context: BadAnnotation.CONTEXT,
      method: BadAnnotation.METHOD,
      path: "",
    };
  }

  static create(p?: IBadAnnotation): BadAnnotation {
    return new BadAnnotation(p);
  }

  static fromAlias(data?: unknown): BadAnnotation {
    return BadAnnotation.create(data as IBadAnnotation);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
