// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// CoreMessages.proto

package webpbpb

import (
	"fmt"
)

type Test3 string

const (
	Test3_test3_1 Test3 = "test3_1"
	Test3_test3_2 Test3 = "test3_2"
	Test3_test3_3 Test3 = "test3_3"
)

type Test5 string

const (
	Test5_test5_1 Test5 = "text1"
	Test5_test5_2 Test5 = "text2"
	Test5_test5_3 Test5 = "test5_3"
)

const (
	Test1Class   = "Test1"
	Test1Method  = "GET"
	Test1Context = "test"
)

type Test1 struct {
	Test1 int64 `webpb:"test1" json:"test1"`
	Test2 int32 `webpb:"test2" json:"test2"`
}

func NewTest1() *Test1 {
	return &Test1{}
}

func (m *Test1) WebpbClass() string   { return Test1Class }
func (m *Test1) WebpbMethod() string  { return Test1Method }
func (m *Test1) WebpbContext() string { return Test1Context }
func (m *Test1) WebpbPath() string {
	return fmt.Sprintf("/test?a=123&b=%v&c=321&d=%v&e=456", m.Test1, m.Test2)
}

const (
	Test2Class   = "Test2"
	Test2Method  = "GET"
	Test2Context = "test"
)

type Test2 struct {
	Test1 int64            `webpb:"test1" json:"test1"`
	Test2 string           `webpb:"test2" json:"test2"`
	Test3 *Test6           `webpb:"test3" json:"test3"`
	Test4 map[int32]*Test1 `webpb:"test4" json:"test4"`
}

func NewTest2() *Test2 {
	return &Test2{}
}

func (m *Test2) WebpbClass() string   { return Test2Class }
func (m *Test2) WebpbMethod() string  { return Test2Method }
func (m *Test2) WebpbContext() string { return Test2Context }
func (m *Test2) WebpbPath() string {
	return fmt.Sprintf("/test/%v?id=%v&data1=%v&data2=%v", m.Test2, m.Test1, m.Test3.Test1, m.Test3.Test2)
}

const (
	Test4Class   = "Test4"
	Test4Method  = ""
	Test4Context = ""
)

type Test4 struct {
	Test1 int64   `webpb:"test1" json:"test1"`
	Test2 int32   `webpb:"test2" json:"test2"`
	Test3 string  `webpb:"test3" json:"test3"`
	Test4 []int64 `webpb:"test4" json:"test4"`
}

func NewTest4() *Test4 {
	return &Test4{}
}

func (m *Test4) WebpbClass() string   { return Test4Class }
func (m *Test4) WebpbMethod() string  { return Test4Method }
func (m *Test4) WebpbContext() string { return Test4Context }
func (m *Test4) WebpbPath() string    { return "" }

const (
	Test6Class   = "Test6"
	Test6Method  = ""
	Test6Context = ""
)

type Test6 struct {
	Test1 string `webpb:"test1" json:"test1"`
	Test2 int32  `webpb:"test2" json:"test2"`
}

func NewTest6() *Test6 {
	return &Test6{}
}

func (m *Test6) WebpbClass() string   { return Test6Class }
func (m *Test6) WebpbMethod() string  { return Test6Method }
func (m *Test6) WebpbContext() string { return Test6Context }
func (m *Test6) WebpbPath() string    { return "" }

const (
	TestClass   = "Test"
	TestMethod  = "GET"
	TestContext = "test"
)

type Test struct {
	Test1  int32              `webpb:"test1" json:"test1"`
	Test2  *Message           `webpb:"test2" json:"test2"`
	Test3  Enum               `webpb:"test3" json:"test3"`
	Test4  *Test4             `webpb:"test4" json:"test4"`
	Test5  map[int64]int32    `webpb:"test5" json:"test5"`
	Test6  map[int32]*Message `webpb:"test6" json:"test6"`
	Test7  *Any               `webpb:"test7" json:"test7"`
	Test8  *Test_NestedTest   `webpb:"test8" json:"test8"`
	Test10 int64              `webpb:"test10" json:"test10"`
	Test11 []*Message         `webpb:"test11" json:"test11"`
	Test12 *Nested            `webpb:"test12" json:"test12"`
	Test13 []*Message         `webpb:"test13" json:"test13"`
	Test14 *Nested            `webpb:"test14" json:"test14"`
	Test15 string             `webpb:"test15" json:"test15"`
	Test16 []byte             `webpb:"test16" json:"test16"`
	Test17 *Test_Test17       `webpb:"test17" json:"test17"`
	Test18 int32              `webpb:"test18" json:"test18"`
	Test19 string             `webpb:"test19" json:"test19"`
}

func NewTest() *Test {
	return &Test{}
}

func (m *Test) WebpbClass() string   { return TestClass }
func (m *Test) WebpbMethod() string  { return TestMethod }
func (m *Test) WebpbContext() string { return TestContext }
func (m *Test) WebpbPath() string    { return fmt.Sprintf("/test/%v", m.Test1) }

const (
	Test_NestedTestClass   = "NestedTest"
	Test_NestedTestMethod  = "GET"
	Test_NestedTestContext = "test"
)

type Test_NestedTest struct {
	Test1 int32 `webpb:"test1" json:"test1"`
}

func NewTest_NestedTest() *Test_NestedTest {
	return &Test_NestedTest{}
}

func (m *Test_NestedTest) WebpbClass() string   { return Test_NestedTestClass }
func (m *Test_NestedTest) WebpbMethod() string  { return Test_NestedTestMethod }
func (m *Test_NestedTest) WebpbContext() string { return Test_NestedTestContext }
func (m *Test_NestedTest) WebpbPath() string    { return fmt.Sprintf("/test/nested/%v", m.Test1) }

const (
	Test_Test17Class   = "Test17"
	Test_Test17Method  = ""
	Test_Test17Context = ""
)

type Test_Test17 struct {
	Test string `webpb:"test" json:"test"`
}

func NewTest_Test17() *Test_Test17 {
	return &Test_Test17{}
}

func (m *Test_Test17) WebpbClass() string   { return Test_Test17Class }
func (m *Test_Test17) WebpbMethod() string  { return Test_Test17Method }
func (m *Test_Test17) WebpbContext() string { return Test_Test17Context }
func (m *Test_Test17) WebpbPath() string    { return "" }
