// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Ignored.proto

package webpbpb

const (
	IgnoreTestClass   = "IgnoreTest"
	IgnoreTestMethod  = ""
	IgnoreTestContext = ""
)

type IgnoreTest struct {
	Test1 int32 `webpb:"test1" json:"test1"`
}

func NewIgnoreTest() *IgnoreTest {
	return &IgnoreTest{}
}

func (m *IgnoreTest) WebpbClass() string   { return IgnoreTestClass }
func (m *IgnoreTest) WebpbMethod() string  { return IgnoreTestMethod }
func (m *IgnoreTest) WebpbContext() string { return IgnoreTestContext }
func (m *IgnoreTest) WebpbPath() string    { return "" }
