/*
 * Copyright (c) 2020 The Webpb Authors, All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * https://github.com/jinganix/webpb
 */

package io.github.jinganix.webpb.utilities.utils;

/** Constants definition. */
public interface Const {

  /** Put at beginning of the file. */
  String HEADER = "Code generated by Webpb compiler, do not edit.";

  /** Put the url after {@link #HEADER}. */
  String GIT_URL = "https://github.com/jinganix/webpb";

  /** Webpb extends protobuf options. */
  String WEBPB_EXTEND = "WebpbExtend.proto";

  /** User custom options definition proto. */
  String WEBPB_OPTIONS = "(.*/)?((?i)webpb[\\._-]?options\\.proto)";

  /** Webpb java runtime package. */
  String RUNTIME_PACKAGE = "io.github.jinganix.webpb.runtime";
}
