// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericJsDts.proto

package constant.tsnumericjsdts;

public interface FooValues {
  int a = 0;
  int b = 1;
  int c = 2;
}
