// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// include2/BaseType.proto

import * as Webpb from "webpb";

export interface IExtends {
  foo_1: number;
  bar_1: string;
}

export class Extends implements IExtends, Webpb.WebpbMessage {
  foo_1!: number;
  bar_1!: string;

  static CLASS = "Extends";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IExtends) {
    Webpb.assign(p, this, []);
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: Extends.CLASS,
      context: Extends.CONTEXT,
      method: Extends.METHOD,
      path: "",
    };
  }

  static create(p?: IExtends): Extends {
    return new Extends(p);
  }

  static fromAlias(data?: unknown): Extends {
    return Extends.create(data as IExtends);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
