// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// NoPackage.proto

import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;

public class NoPackage implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META = new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private Integer foo_1;

  private String bar_2;

  private NoPackageTest test;

  public NoPackage() {
  }

  public NoPackage(Integer foo_1, String bar_2, NoPackageTest test) {
    this.foo_1 = foo_1;
    this.bar_2 = bar_2;
    this.test = test;
  }

  public Integer getFoo_1() {
    return this.foo_1;
  }

  public NoPackage setFoo_1(Integer foo_1) {
    this.foo_1 = foo_1;
    return this;
  }

  public String getBar_2() {
    return this.bar_2;
  }

  public NoPackage setBar_2(String bar_2) {
    this.bar_2 = bar_2;
    return this;
  }

  public NoPackageTest getTest() {
    return this.test;
  }

  public NoPackage setTest(NoPackageTest test) {
    this.test = test;
    return this;
  }
}
