// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericDebugEnum.proto

package constant.tsnumericdebug;

public interface BarNames {
  String x = "x";
  String y = "y";
  String z = "z";
}
