// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericDebugEnum.proto

package constant.tsnumericdebug;

public interface BarValues {
  int x = 0;
  int y = 1;
  int z = 2;
}
