// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Test5.proto

export enum Test {
  DEFAULT = 0,
  OTHER = 100,
}

export const enum ConstTest {
  DEFAULT = 0,
  OTHER = 100,
}
