// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Test1.proto

import * as Webpb from "webpb";

export interface ITest {
}

export class Test implements ITest, Webpb.WebpbMessage {
  webpbMeta: () => Webpb.WebpbMeta;

  protected constructor() {
    this.webpbMeta = () => ({
      class: "Test",
      context: "",
      method: "",
      path: "",
    }) as Webpb.WebpbMeta;
  }

  static create(): Test {
    return new Test();
  }

  static fromAlias(_data?: Record<string, unknown>): Test {
    return Test.create();
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
