// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Test1.proto

import * as Webpb from "webpb";

export interface ITest {
}

export class Test implements ITest, Webpb.WebpbMessage {
  webpbMeta: () => Webpb.WebpbMeta;

  protected constructor(p?: ITest) {
    Webpb.assign(p, this, []);
    this.webpbMeta = () =>
      ({
        class: "Test",
        context: "",
        method: "",
        path: "",
      }) as Webpb.WebpbMeta;
  }

  static create(p?: ITest): Test {
    return new Test(p);
  }

  static fromAlias(data?: unknown): ITest {
    return Test.create(data as ITest);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
