// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Test5.proto

export enum Test {
  DEFAULT = 0,
  OTHER = 100,
}

export const TestValues = [
  Test.DEFAULT,
  Test.OTHER,
];

export const enum ConstTest {
  DEFAULT = 0,
  OTHER = 100,
}

export const ConstTestValues = [
  ConstTest.DEFAULT,
  ConstTest.OTHER,
];
