// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// FileDefaultConstEnum.proto

package constant.enum2;

public interface ConstEnum2Values {
  int DEFAULT = 0;
}
