// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// BarEnumShim.proto

import * as Webpb from "webpb";

export type { Bar } from "./Bar";

export { BarValues } from "./Bar.js";

export interface IFooPb {
  type?: Bar | null;
}

export class FooPb implements IFooPb, Webpb.WebpbMessage {
  type?: Bar | null;
  webpbMeta: () => Webpb.WebpbMeta;

  static CLASS = "FooPb";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IFooPb) {
    Webpb.assign(p, this, []);
    this.webpbMeta = () =>
      ({
        class: "FooPb",
        context: "",
        method: "",
        path: "",
      }) as Webpb.WebpbMeta;
  }

  static create(p?: IFooPb): FooPb {
    return new FooPb(p);
  }

  static fromAlias(data?: unknown): FooPb {
    return FooPb.create(data as IFooPb);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
