// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericJsDts.proto

export const enum Foo {
  a = 0,
  b = 1,
  c = 2,
}

export declare const FooValues: readonly Foo[];
