// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// FooBarJsDts.proto

import * as Webpb from "webpb";
import type { Bar } from "./BarEnum";

export interface IFooBarPb {
  type?: Bar | null;
}

export class FooBarPb implements IFooBarPb, Webpb.WebpbMessage {
  type?: Bar | null;
  webpbMeta: () => Webpb.WebpbMeta;

  static CLASS = "FooBarPb";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IFooBarPb) {
    Webpb.assign(p, this, []);
    this.webpbMeta = () =>
      ({
        class: "FooBarPb",
        context: "",
        method: "",
        path: "",
      }) as Webpb.WebpbMeta;
  }

  static create(p?: IFooBarPb): FooBarPb {
    return new FooBarPb(p);
  }

  static fromAlias(data?: unknown): FooBarPb {
    return FooBarPb.create(data as IFooBarPb);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
