// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericDebugEnum.proto

export enum LogLevel {
  info = 0,
  warn = 1,
  error = 2,
}

export const LogLevelValues = [0, 1, 2];

export const LogLevelByName = {
  error: 2,
  info: 0,
  warn: 1,
};

export const LogLevelByValue = {
  0: "info",
  1: "warn",
  2: "error",
};
