// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericDebugEnum.proto

export enum Bar {
  x = 0,
  y = 1,
  z = 2,
}

export const BarValues: readonly Bar[] = [0, 1, 2];

export const BarByName = {
  x: 0,
  y: 1,
  z: 2,
} as const;

export type BarName = keyof typeof BarByName;

export const BarByValue = {
  0: "x",
  1: "y",
  2: "z",
} as const;

export type BarByValueKey = keyof typeof BarByValue;

export function barFromName(name: BarName): Bar {
  return BarByName[name];
}

export function barToName(value: Bar): string {
  return BarByValue[value];
}
