// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericEnum.proto

export const enum Foo {
  a = 0,
  b = 1,
  c = 2,
}

export const FooValues: readonly Foo[] = [0, 1, 2];

export const FooByName = {
  a: 0,
  b: 1,
  c: 2,
} as const;

export type FooName = keyof typeof FooByName;

export function fooFromName(name: FooName): Foo {
  return FooByName[name];
}
