// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// BarEnumTsAndJs.proto

package webpbpb

type Bar int32

const (
	Bar_a Bar = 0
	Bar_b Bar = 1
	Bar_c Bar = 2
)

var BarNames = map[Bar]string{
	Bar_a: "a",
	Bar_b: "b",
	Bar_c: "c",
}

func (x Bar) String() string {
	if name, ok := BarNames[x]; ok {
		return name
	}
	return ""
}

const (
	FooPbClass   = "FooPb"
	FooPbMethod  = ""
	FooPbContext = ""
)

type FooPb struct {
	Type *Bar `webpb:"type" json:"type"`
}

func NewFooPb() *FooPb {
	return &FooPb{}
}

func (m *FooPb) WebpbClass() string   { return FooPbClass }
func (m *FooPb) WebpbMethod() string  { return FooPbMethod }
func (m *FooPb) WebpbContext() string { return FooPbContext }
func (m *FooPb) WebpbPath() string    { return "" }
