// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// BazEnumJsDts.proto

package webpbpb

type Baz int32

const (
	Baz_a Baz = 0
	Baz_b Baz = 1
	Baz_c Baz = 2
)

var BazNames = map[Baz]string{
	Baz_a: "a",
	Baz_b: "b",
	Baz_c: "c",
}

func (x Baz) String() string {
	if name, ok := BazNames[x]; ok {
		return name
	}
	return ""
}
