// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// EnumDefaultConst.proto

package webpbpb

type ConstEnum4 int32

const (
	ConstEnum4_DEFAULT ConstEnum4 = 0
	ConstEnum4_OTHER   ConstEnum4 = 1
)

var ConstEnum4Names = map[ConstEnum4]string{
	ConstEnum4_DEFAULT: "DEFAULT",
	ConstEnum4_OTHER:   "OTHER",
}

func (x ConstEnum4) String() string {
	if name, ok := ConstEnum4Names[x]; ok {
		return name
	}
	return ""
}
