// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// FileDefaultConstEnum.proto

package webpbpb

type ConstEnum2 int32

const (
	ConstEnum2_DEFAULT ConstEnum2 = 0
)

var ConstEnum2Names = map[ConstEnum2]string{
	ConstEnum2_DEFAULT: "DEFAULT",
}

func (x ConstEnum2) String() string {
	if name, ok := ConstEnum2Names[x]; ok {
		return name
	}
	return ""
}
