// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// FooBarJsDts.proto

package webpbpb

const (
	FooBarPbClass   = "FooBarPb"
	FooBarPbMethod  = ""
	FooBarPbContext = ""
)

type FooBarPb struct {
	Type *Bar `webpb:"type" json:"type"`
}

func NewFooBarPb() *FooBarPb {
	return &FooBarPb{}
}

func (m *FooBarPb) WebpbClass() string   { return FooBarPbClass }
func (m *FooBarPb) WebpbMethod() string  { return FooBarPbMethod }
func (m *FooBarPb) WebpbContext() string { return FooBarPbContext }
func (m *FooBarPb) WebpbPath() string    { return "" }
