// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// MapValueJsDts.proto

package webpbpb

type Baz int32

const (
	Baz_x Baz = 0
	Baz_y Baz = 1
)

var BazNames = map[Baz]string{
	Baz_x: "x",
	Baz_y: "y",
}

func (x Baz) String() string {
	if name, ok := BazNames[x]; ok {
		return name
	}
	return ""
}

const (
	MapValueJsDtsPbClass   = "MapValueJsDtsPb"
	MapValueJsDtsPbMethod  = ""
	MapValueJsDtsPbContext = ""
)

type MapValueJsDtsPb struct {
	Sort map[string]Baz `webpb:"sort" json:"sort"`
}

func NewMapValueJsDtsPb() *MapValueJsDtsPb {
	return &MapValueJsDtsPb{}
}

func (m *MapValueJsDtsPb) WebpbClass() string   { return MapValueJsDtsPbClass }
func (m *MapValueJsDtsPb) WebpbMethod() string  { return MapValueJsDtsPbMethod }
func (m *MapValueJsDtsPb) WebpbContext() string { return MapValueJsDtsPbContext }
func (m *MapValueJsDtsPb) WebpbPath() string    { return "" }
