// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// MessageDefaultConst.proto

package webpbpb

type ConstEnum3 int32

const (
	ConstEnum3_DEFAULT ConstEnum3 = 0
)

var ConstEnum3Names = map[ConstEnum3]string{
	ConstEnum3_DEFAULT: "DEFAULT",
}

func (x ConstEnum3) String() string {
	if name, ok := ConstEnum3Names[x]; ok {
		return name
	}
	return ""
}
