// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericDebugEnum.proto

package webpbpb

type Bar int32

const (
	Bar_x Bar = 0
	Bar_y Bar = 1
	Bar_z Bar = 2
)

var BarNames = map[Bar]string{
	Bar_x: "x",
	Bar_y: "y",
	Bar_z: "z",
}

func (x Bar) String() string {
	if name, ok := BarNames[x]; ok {
		return name
	}
	return ""
}
