// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsStringValuesEnum.proto

package webpbpb

type TokenType string

const (
	TokenType_BEARER TokenType = "Bearer"
	TokenType_ACCESS TokenType = "Access"
)
