// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// ExtendsTargetNotFound.proto

package webpbpb

const (
	ImportPathNotFoundClass   = "ImportPathNotFound"
	ImportPathNotFoundMethod  = ""
	ImportPathNotFoundContext = ""
)

type ImportPathNotFound struct {
	Foo2 *int32  `webpb:"foo_2" json:"foo_2"`
	Bar2 *string `webpb:"bar_2" json:"bar_2"`
}

func NewImportPathNotFound() *ImportPathNotFound {
	return &ImportPathNotFound{}
}

func (m *ImportPathNotFound) WebpbClass() string   { return ImportPathNotFoundClass }
func (m *ImportPathNotFound) WebpbMethod() string  { return ImportPathNotFoundMethod }
func (m *ImportPathNotFound) WebpbContext() string { return ImportPathNotFoundContext }
func (m *ImportPathNotFound) WebpbPath() string    { return "" }
