// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// AugmentStatus.proto

package augment.test.user;

import io.github.jinganix.webpb.runtime.enumeration.Enumeration;

public enum AugmentStatus implements Enumeration<Integer> {
  AUGMENT_UNKNOWN(0),
  AUGMENT_ACTIVE(1);

  private Integer value;

  AugmentStatus(Integer value) {
    this.value = value;
  }

  public static AugmentStatus fromValue(Integer value) {
    switch (value) {
      case 0:
        return AUGMENT_UNKNOWN;
      case 1:
        return AUGMENT_ACTIVE;
      default:
        return null;
    }
  }

  @Override
  public Integer getValue() {
    return this.value;
  }
}
