// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// AugmentStatus.proto

package augment.test.user;

import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;

public class AugmentExtraPb implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META =
      new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private Long value;

  public AugmentExtraPb() {}

  public AugmentExtraPb(Long value) {
    this.value = value;
  }

  public Long getValue() {
    return this.value;
  }

  public AugmentExtraPb setValue(Long value) {
    this.value = value;
    return this;
  }
}
