// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// SubTypeSubValue.proto

package extend.test.main;

public interface SubTypeSubValueTypeValues {
  int subTypeSubValue0 = 0;
  int subTypeSubValue1 = 1;
  int subTypeSubValue2 = 2;
}
