// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// SubTypeSubValue.proto

package extend.test.main;

import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;
import io.github.jinganix.webpb.runtime.WebpbSubValue;

@WebpbSubValue("0")
@WebpbSubValue("a")
public class SubTypeSubValue6 extends SubTypeSubValueSuper implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META = new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private Integer value;

  public SubTypeSubValue6() {
  }

  public SubTypeSubValue6(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return this.value;
  }

  public SubTypeSubValue6 setValue(Integer value) {
    this.value = value;
    return this;
  }
}
