// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// SubTypeSubValue.proto

package extend.test.main;

import io.github.jinganix.webpb.runtime.enumeration.Enumeration;

public enum SubTypeSubValueType implements Enumeration<Integer> {

  subTypeSubValue0(0),
  subTypeSubValue1(1),
  subTypeSubValue2(2);

  private Integer value;

  SubTypeSubValueType(Integer value) {
    this.value = value;
  }

  public static SubTypeSubValueType fromValue(Integer value) {
    switch (value) {
    case 0:
      return subTypeSubValue0;
    case 1:
      return subTypeSubValue1;
    case 2:
      return subTypeSubValue2;
    default:
      return null;
    }
  }

  @Override
  public Integer getValue() {
    return this.value;
  }
}
