// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Test5.proto

package test5;

import io.github.jinganix.webpb.runtime.enumeration.Enumeration;
import lombok.ToString;

@ToString
public enum Test implements Enumeration<Integer> {

  DEFAULT(0),
  OTHER(100);

  private Integer value;

  Test(Integer value) {
    this.value = value;
  }

  public static Test fromValue(Integer value) {
    switch (value) {
    case 0:
      return DEFAULT;
    case 100:
      return OTHER;
    default:
      return null;
    }
  }

  @Override
  public Integer getValue() {
    return this.value;
  }
}
