// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// include2/BaseType.proto

package webpbpb

const (
	ExtendsClass   = "Extends"
	ExtendsMethod  = ""
	ExtendsContext = ""
)

type Extends struct {
	Foo1 int32  `webpb:"foo_1" json:"foo_1"`
	Bar1 string `webpb:"bar_1" json:"bar_1"`
}

func NewExtends() *Extends {
	return &Extends{}
}

func (m *Extends) WebpbClass() string   { return ExtendsClass }
func (m *Extends) WebpbMethod() string  { return ExtendsMethod }
func (m *Extends) WebpbContext() string { return ExtendsContext }
func (m *Extends) WebpbPath() string    { return "" }
