// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// BasicExtends.proto

package webpbpb

const (
	Main1Class   = "Main1"
	Main1Method  = ""
	Main1Context = ""
)

type Main1 struct {
	Foo1 int32  `webpb:"foo_1" json:"foo_1"`
	Bar1 string `webpb:"bar_1" json:"bar_1"`
	Foo2 int32  `webpb:"foo_2" json:"foo_2"`
	Bar2 string `webpb:"bar_2" json:"bar_2"`
}

func NewMain1() *Main1 {
	return &Main1{}
}

func (m *Main1) WebpbClass() string   { return Main1Class }
func (m *Main1) WebpbMethod() string  { return Main1Method }
func (m *Main1) WebpbContext() string { return Main1Context }
func (m *Main1) WebpbPath() string    { return "" }

const (
	Main2Class   = "Main2"
	Main2Method  = ""
	Main2Context = ""
)

type Main2 struct {
	Foo1 int32  `webpb:"foo_1" json:"foo_1"`
	Bar1 string `webpb:"bar_1" json:"bar_1"`
	Foo2 int32  `webpb:"foo_2" json:"foo_2"`
	Bar2 string `webpb:"bar_2" json:"bar_2"`
}

func NewMain2() *Main2 {
	return &Main2{}
}

func (m *Main2) WebpbClass() string   { return Main2Class }
func (m *Main2) WebpbMethod() string  { return Main2Method }
func (m *Main2) WebpbContext() string { return Main2Context }
func (m *Main2) WebpbPath() string    { return "" }

const (
	Main3Class   = "Main3"
	Main3Method  = ""
	Main3Context = ""
)

type Main3 struct {
	Foo1 int32  `webpb:"foo_1" json:"foo_1"`
	Bar1 string `webpb:"bar_1" json:"bar_1"`
	Foo2 int32  `webpb:"foo_2" json:"foo_2"`
	Bar2 string `webpb:"bar_2" json:"bar_2"`
}

func NewMain3() *Main3 {
	return &Main3{}
}

func (m *Main3) WebpbClass() string   { return Main3Class }
func (m *Main3) WebpbMethod() string  { return Main3Method }
func (m *Main3) WebpbContext() string { return Main3Context }
func (m *Main3) WebpbPath() string    { return "" }

const (
	Main4Class   = "Main4"
	Main4Method  = ""
	Main4Context = ""
)

type Main4 struct {
	Foo2 int32  `webpb:"foo_2" json:"foo_2"`
	Bar2 string `webpb:"bar_2" json:"bar_2"`
}

func NewMain4() *Main4 {
	return &Main4{}
}

func (m *Main4) WebpbClass() string   { return Main4Class }
func (m *Main4) WebpbMethod() string  { return Main4Method }
func (m *Main4) WebpbContext() string { return Main4Context }
func (m *Main4) WebpbPath() string    { return "" }
