// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// CrossFileEnum.proto

package webpbpb

type Another int32

const (
	Another_a Another = 0
)

var AnotherNames = map[Another]string{
	Another_a: "a",
}

func (x Another) String() string {
	if name, ok := AnotherNames[x]; ok {
		return name
	}
	return ""
}
