rootProject.name = "webpb"
include(":lib:commons")
include(":lib:proto")
include(":lib:tests")
include(":lib:utilities")
include(":plugin")
include(":runtime:java")
include(":runtime:processor")
include(":runtime:ts")
include(":sample:proto")
include(":sample:backend")
