// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Include.proto

package include;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.github.jinganix.webpb.runtime.enumeration.Enumeration;
import io.github.jinganix.webpb.runtime.enumeration.EnumerationDeserializer;
import io.github.jinganix.webpb.runtime.enumeration.EnumerationSerializer;

@JsonDeserialize(using = EnumerationDeserializer.class)
@JsonSerialize(using = EnumerationSerializer.class)
public enum Enum implements Enumeration<Integer> {

  DEFAULT(0);

  private Integer value;

  Enum(Integer value) {
    this.value = value;
  }

  public static Enum fromValue(Integer value) {
    switch (value) {
    case 0:
      return DEFAULT;
    default:
      return null;
    }
  }

  @Override
  public Integer getValue() {
    return this.value;
  }
}
