// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// ExtendsTargetNotFound.proto

import * as Webpb from "webpb";
import * as BadImport from "./BadImport";

export interface IImportPathNotFound extends BadImport.IExtends {
  foo_2: number;
  bar_2: string;
}

export class ImportPathNotFound extends BadImport.Extends implements IImportPathNotFound, Webpb.WebpbMessage {
  foo_2!: number;
  bar_2!: string;

  static CLASS = "ImportPathNotFound";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IImportPathNotFound) {
    super();
    Webpb.assign(p, this, []);
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: ImportPathNotFound.CLASS,
      context: ImportPathNotFound.CONTEXT,
      method: ImportPathNotFound.METHOD,
      path: "",
    };
  }

  static create(p?: IImportPathNotFound): ImportPathNotFound {
    return new ImportPathNotFound(p);
  }

  static fromAlias(data?: unknown): ImportPathNotFound {
    return ImportPathNotFound.create(data as IImportPathNotFound);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
