// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// AliasReserve.proto

package webpbpb

const (
	AliasReserveParentClass   = "AliasReserveParent"
	AliasReserveParentMethod  = ""
	AliasReserveParentContext = ""
)

type AliasReserveParent struct {
	Foo1 int32 `webpb:"foo_1" json:"foo_1"`
}

func NewAliasReserveParent() *AliasReserveParent {
	return &AliasReserveParent{}
}

func (m *AliasReserveParent) WebpbClass() string   { return AliasReserveParentClass }
func (m *AliasReserveParent) WebpbMethod() string  { return AliasReserveParentMethod }
func (m *AliasReserveParent) WebpbContext() string { return AliasReserveParentContext }
func (m *AliasReserveParent) WebpbPath() string    { return "" }

const (
	AliasReserveChildClass   = "AliasReserveChild"
	AliasReserveChildMethod  = ""
	AliasReserveChildContext = ""
)

type AliasReserveChild struct {
	Foo1 int32 `webpb:"foo_1" json:"foo_1"`
	Foo2 int32 `webpb:"foo_2" json:"foo_2"`
}

func NewAliasReserveChild() *AliasReserveChild {
	return &AliasReserveChild{}
}

func (m *AliasReserveChild) WebpbClass() string   { return AliasReserveChildClass }
func (m *AliasReserveChild) WebpbMethod() string  { return AliasReserveChildMethod }
func (m *AliasReserveChild) WebpbContext() string { return AliasReserveChildContext }
func (m *AliasReserveChild) WebpbPath() string    { return "" }
