// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// ExtendsHierarchy.proto

package webpbpb

const (
	Level3Class   = "Level3"
	Level3Method  = ""
	Level3Context = ""
)

type Level3 struct {
	Foo1 int32 `webpb:"foo_1" json:"foo_1"`
}

func NewLevel3() *Level3 {
	return &Level3{}
}

func (m *Level3) WebpbClass() string   { return Level3Class }
func (m *Level3) WebpbMethod() string  { return Level3Method }
func (m *Level3) WebpbContext() string { return Level3Context }
func (m *Level3) WebpbPath() string    { return "" }

const (
	Level2Class   = "Level2"
	Level2Method  = ""
	Level2Context = ""
)

type Level2 struct {
	Foo1 int32 `webpb:"foo_1" json:"foo_1"`
	Foo2 int32 `webpb:"foo_2" json:"foo_2"`
}

func NewLevel2() *Level2 {
	return &Level2{}
}

func (m *Level2) WebpbClass() string   { return Level2Class }
func (m *Level2) WebpbMethod() string  { return Level2Method }
func (m *Level2) WebpbContext() string { return Level2Context }
func (m *Level2) WebpbPath() string    { return "" }

const (
	Level1Class   = "Level1"
	Level1Method  = ""
	Level1Context = ""
)

type Level1 struct {
	Foo1 int32 `webpb:"foo_1" json:"foo_1"`
	Foo2 int32 `webpb:"foo_2" json:"foo_2"`
	Foo3 int32 `webpb:"foo_3" json:"foo_3"`
	Foo4 int64 `webpb:"foo_4" json:"foo_4"`
}

func NewLevel1() *Level1 {
	return &Level1{}
}

func (m *Level1) WebpbClass() string   { return Level1Class }
func (m *Level1) WebpbMethod() string  { return Level1Method }
func (m *Level1) WebpbContext() string { return Level1Context }
func (m *Level1) WebpbPath() string    { return "" }
