// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// ConstEnum1.proto

export const enum ConstEnum1 {
  DEFAULT = 0,
}

export const ConstEnum1Values = [
  ConstEnum1.DEFAULT,
];

export enum EnumConstEnum1 {
  DEFAULT = 0,
}

export const EnumConstEnum1Values = [
  EnumConstEnum1.DEFAULT,
];
