// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// ConstEnum3.proto

export enum ConstEnum3 {
  DEFAULT = 0,
}

export const enum ConstConstEnum3 {
  DEFAULT = 0,
}
