// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// ConstEnum2.proto

export const enum ConstEnum2 {
  DEFAULT = 0,
}

export enum EnumConstEnum2 {
  DEFAULT = 0,
}
