// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// ConstEnum1.proto

export const enum ConstEnum1 {
  DEFAULT = 0,
}

export enum EnumConstEnum1 {
  DEFAULT = 0,
}
