// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// PrimitiveTypes.proto

package primitive;

import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;
import java.util.List;

public class PrimitiveTypes implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META =
      new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private Float float_field;

  private Double double_field;

  private Integer uint32_field;

  private Long uint64_field;

  private Integer sint32_field;

  private Long sint64_field;

  private Integer fixed32_field;

  private Long fixed64_field;

  private Integer sfixed32_field;

  private Long sfixed64_field;

  private List<Float> repeated_float;

  public PrimitiveTypes() {}

  public Float getFloat_field() {
    return this.float_field;
  }

  public PrimitiveTypes setFloat_field(Float float_field) {
    this.float_field = float_field;
    return this;
  }

  public Double getDouble_field() {
    return this.double_field;
  }

  public PrimitiveTypes setDouble_field(Double double_field) {
    this.double_field = double_field;
    return this;
  }

  public Integer getUint32_field() {
    return this.uint32_field;
  }

  public PrimitiveTypes setUint32_field(Integer uint32_field) {
    this.uint32_field = uint32_field;
    return this;
  }

  public Long getUint64_field() {
    return this.uint64_field;
  }

  public PrimitiveTypes setUint64_field(Long uint64_field) {
    this.uint64_field = uint64_field;
    return this;
  }

  public Integer getSint32_field() {
    return this.sint32_field;
  }

  public PrimitiveTypes setSint32_field(Integer sint32_field) {
    this.sint32_field = sint32_field;
    return this;
  }

  public Long getSint64_field() {
    return this.sint64_field;
  }

  public PrimitiveTypes setSint64_field(Long sint64_field) {
    this.sint64_field = sint64_field;
    return this;
  }

  public Integer getFixed32_field() {
    return this.fixed32_field;
  }

  public PrimitiveTypes setFixed32_field(Integer fixed32_field) {
    this.fixed32_field = fixed32_field;
    return this;
  }

  public Long getFixed64_field() {
    return this.fixed64_field;
  }

  public PrimitiveTypes setFixed64_field(Long fixed64_field) {
    this.fixed64_field = fixed64_field;
    return this;
  }

  public Integer getSfixed32_field() {
    return this.sfixed32_field;
  }

  public PrimitiveTypes setSfixed32_field(Integer sfixed32_field) {
    this.sfixed32_field = sfixed32_field;
    return this;
  }

  public Long getSfixed64_field() {
    return this.sfixed64_field;
  }

  public PrimitiveTypes setSfixed64_field(Long sfixed64_field) {
    this.sfixed64_field = sfixed64_field;
    return this;
  }

  public List<Float> getRepeated_float() {
    return this.repeated_float;
  }

  public PrimitiveTypes setRepeated_float(List<Float> repeated_float) {
    this.repeated_float = repeated_float;
    return this;
  }
}
