// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// RepeatedMessageValid.proto

package repeated_message_valid;

import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.util.List;

public class RepeatedMessageValid implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META =
      new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  @NotNull
  @Size(min = 1)
  private List<@Valid Item> items;

  @Valid private List<String> tags;

  public RepeatedMessageValid() {}

  public RepeatedMessageValid(List<@Valid Item> items, List<String> tags) {
    this.items = items;
    this.tags = tags;
  }

  public List<@Valid Item> getItems() {
    return this.items;
  }

  public RepeatedMessageValid setItems(List<@Valid Item> items) {
    this.items = items;
    return this;
  }

  public List<String> getTags() {
    return this.tags;
  }

  public RepeatedMessageValid setTags(List<String> tags) {
    this.tags = tags;
    return this;
  }
}
