// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// FieldOpts.proto

package auto.alias.field;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;
import java.util.List;
import java.util.Map;

public class Level1 implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META = new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  @JsonProperty("a")
  private Integer test1;

  private Level2 test2;

  private List<Level2> test3;

  private Level3 test4;

  @JsonProperty("e")
  private Map<Integer, Level3> test5;

  private Map<String, Level3> test6;

  public Level1() {
  }

  public Integer getTest1() {
    return this.test1;
  }

  public Level1 setTest1(Integer test1) {
    this.test1 = test1;
    return this;
  }

  public Level2 getTest2() {
    return this.test2;
  }

  public Level1 setTest2(Level2 test2) {
    this.test2 = test2;
    return this;
  }

  public List<Level2> getTest3() {
    return this.test3;
  }

  public Level1 setTest3(List<Level2> test3) {
    this.test3 = test3;
    return this;
  }

  public Level3 getTest4() {
    return this.test4;
  }

  public Level1 setTest4(Level3 test4) {
    this.test4 = test4;
    return this;
  }

  public Map<Integer, Level3> getTest5() {
    return this.test5;
  }

  public Level1 setTest5(Map<Integer, Level3> test5) {
    this.test5 = test5;
    return this;
  }

  public Map<String, Level3> getTest6() {
    return this.test6;
  }

  public Level1 setTest6(Map<String, Level3> test6) {
    this.test6 = test6;
    return this;
  }
}
