// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// AugmentNotOpen.proto

package webpbpb

const (
	ClosedUserPbClass   = "ClosedUserPb"
	ClosedUserPbMethod  = ""
	ClosedUserPbContext = ""
)

type ClosedUserPb struct {
	Id      int64 `webpb:"id" json:"id"`
	StaffId int64 `webpb:"staffId" json:"staffId"`
}

func NewClosedUserPb() *ClosedUserPb {
	return &ClosedUserPb{}
}

func (m *ClosedUserPb) WebpbClass() string   { return ClosedUserPbClass }
func (m *ClosedUserPb) WebpbMethod() string  { return ClosedUserPbMethod }
func (m *ClosedUserPb) WebpbContext() string { return ClosedUserPbContext }
func (m *ClosedUserPb) WebpbPath() string    { return "" }
