// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// AugmentFieldReserve.proto

package webpbpb

const (
	ReservedUserPbClass   = "ReservedUserPb"
	ReservedUserPbMethod  = ""
	ReservedUserPbContext = ""
)

type ReservedUserPb struct {
	Id      int64 `webpb:"id" json:"id"`
	StaffId int64 `webpb:"staffId" json:"staffId"`
}

func NewReservedUserPb() *ReservedUserPb {
	return &ReservedUserPb{}
}

func (m *ReservedUserPb) WebpbClass() string   { return ReservedUserPbClass }
func (m *ReservedUserPb) WebpbMethod() string  { return ReservedUserPbMethod }
func (m *ReservedUserPb) WebpbContext() string { return ReservedUserPbContext }
func (m *ReservedUserPb) WebpbPath() string    { return "" }
