// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// BadClassOrInterface.proto

package webpbpb

const (
	BadAnnotationClass   = "BadAnnotation"
	BadAnnotationMethod  = ""
	BadAnnotationContext = ""
)

type BadAnnotation struct {
	Foo2 int32  `webpb:"foo_2" json:"foo_2"`
	Bar2 string `webpb:"bar_2" json:"bar_2"`
}

func NewBadAnnotation() *BadAnnotation {
	return &BadAnnotation{}
}

func (m *BadAnnotation) WebpbClass() string   { return BadAnnotationClass }
func (m *BadAnnotation) WebpbMethod() string  { return BadAnnotationMethod }
func (m *BadAnnotation) WebpbContext() string { return BadAnnotationContext }
func (m *BadAnnotation) WebpbPath() string    { return "" }
