// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// BadExtends.proto

package webpbpb

const (
	BadExtendsClass   = "BadExtends"
	BadExtendsMethod  = ""
	BadExtendsContext = ""
)

type BadExtends struct {
	Value int32 `webpb:"value" json:"value"`
}

func NewBadExtends() *BadExtends {
	return &BadExtends{}
}

func (m *BadExtends) WebpbClass() string   { return BadExtendsClass }
func (m *BadExtends) WebpbMethod() string  { return BadExtendsMethod }
func (m *BadExtends) WebpbContext() string { return BadExtendsContext }
func (m *BadExtends) WebpbPath() string    { return "" }
