// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// DuplicatedExtendsFields.proto

package webpbpb

const (
	Test1Class   = "Test1"
	Test1Method  = ""
	Test1Context = ""
)

type Test1 struct {
	Foo int32 `webpb:"foo" json:"foo"`
}

func NewTest1() *Test1 {
	return &Test1{}
}

func (m *Test1) WebpbClass() string   { return Test1Class }
func (m *Test1) WebpbMethod() string  { return Test1Method }
func (m *Test1) WebpbContext() string { return Test1Context }
func (m *Test1) WebpbPath() string    { return "" }

const (
	Test2Class   = "Test2"
	Test2Method  = ""
	Test2Context = ""
)

type Test2 struct {
	Foo int32 `webpb:"foo" json:"foo"`
	Foo int32 `webpb:"foo" json:"foo"`
}

func NewTest2() *Test2 {
	return &Test2{}
}

func (m *Test2) WebpbClass() string   { return Test2Class }
func (m *Test2) WebpbMethod() string  { return Test2Method }
func (m *Test2) WebpbContext() string { return Test2Context }
func (m *Test2) WebpbPath() string    { return "" }
