// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// FileOpts.proto

package auto.alias.file;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;

public class Level3 implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META = new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  @JsonProperty("a")
  private Integer test1;

  public Level3() {
  }

  public Level3(Integer test1) {
    this.test1 = test1;
  }

  public Integer getTest1() {
    return this.test1;
  }

  public Level3 setTest1(Integer test1) {
    this.test1 = test1;
    return this;
  }
}
