// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// AugmentStatus.proto

package webpbpb

type AugmentStatus int32

const (
	AugmentStatus_AUGMENT_UNKNOWN AugmentStatus = 0
	AugmentStatus_AUGMENT_ACTIVE  AugmentStatus = 1
)

var AugmentStatusNames = map[AugmentStatus]string{
	AugmentStatus_AUGMENT_UNKNOWN: "AUGMENT_UNKNOWN",
	AugmentStatus_AUGMENT_ACTIVE:  "AUGMENT_ACTIVE",
}

func (x AugmentStatus) String() string {
	if name, ok := AugmentStatusNames[x]; ok {
		return name
	}
	return ""
}

const (
	AugmentExtraPbClass   = "AugmentExtraPb"
	AugmentExtraPbMethod  = ""
	AugmentExtraPbContext = ""
)

type AugmentExtraPb struct {
	Value int64 `webpb:"value" json:"value"`
}

func NewAugmentExtraPb() *AugmentExtraPb {
	return &AugmentExtraPb{}
}

func (m *AugmentExtraPb) WebpbClass() string   { return AugmentExtraPbClass }
func (m *AugmentExtraPb) WebpbMethod() string  { return AugmentExtraPbMethod }
func (m *AugmentExtraPb) WebpbContext() string { return AugmentExtraPbContext }
func (m *AugmentExtraPb) WebpbPath() string    { return "" }
