// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// User.proto

package webpbpb

const (
	UserPbClass   = "UserPb"
	UserPbMethod  = ""
	UserPbContext = ""
)

type UserPb struct {
	Id          int64  `webpb:"id" json:"id"`
	Username    string `webpb:"username" json:"username"`
	StaffId     int64  `webpb:"staffId" json:"staffId"`
	DisplayName string `webpb:"displayName" json:"displayName"`
}

func NewUserPb() *UserPb {
	return &UserPb{}
}

func (m *UserPb) WebpbClass() string   { return UserPbClass }
func (m *UserPb) WebpbMethod() string  { return UserPbMethod }
func (m *UserPb) WebpbContext() string { return UserPbContext }
func (m *UserPb) WebpbPath() string    { return "" }

const (
	UserDetailsPbClass   = "UserDetailsPb"
	UserDetailsPbMethod  = ""
	UserDetailsPbContext = ""
)

type UserDetailsPb struct {
	Id          int64   `webpb:"id" json:"id"`
	Username    string  `webpb:"username" json:"username"`
	StaffId     int64   `webpb:"staffId" json:"staffId"`
	DisplayName string  `webpb:"displayName" json:"displayName"`
	RoleIds     []int64 `webpb:"roleIds" json:"roleIds"`
}

func NewUserDetailsPb() *UserDetailsPb {
	return &UserDetailsPb{}
}

func (m *UserDetailsPb) WebpbClass() string   { return UserDetailsPbClass }
func (m *UserDetailsPb) WebpbMethod() string  { return UserDetailsPbMethod }
func (m *UserDetailsPb) WebpbContext() string { return UserDetailsPbContext }
func (m *UserDetailsPb) WebpbPath() string    { return "" }
