// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// MapValueTest.proto

import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;
import java.util.Map;

public class MapValueTestPb implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META = new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private Map<String, Direction> sort;

  public MapValueTestPb() {
  }

  public MapValueTestPb(Map<String, Direction> sort) {
    this.sort = sort;
  }

  public Map<String, Direction> getSort() {
    return this.sort;
  }

  public MapValueTestPb setSort(Map<String, Direction> sort) {
    this.sort = sort;
    return this;
  }
}
