// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// BarEnumShim.proto

package constant.barenum;

public interface BarNames {
  String a = "a";
  String b = "b";
  String c = "c";
}
