// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// BarEnumShim.proto

package constant.barenum;

public interface BarValues {
  int a = 0;
  int b = 1;
  int c = 2;
}
