// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// SubTypeSubValue.proto

package extend.test.main;

public interface SubTypeSubValueTypeNames {
  String subTypeSubValue0 = "subTypeSubValue0";
  String subTypeSubValue1 = "subTypeSubValue1";
  String subTypeSubValue2 = "subTypeSubValue2";
}
