// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// RepeatedFieldTypes.proto

package repeated_field_types;

import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;
import java.util.Collection;
import java.util.List;
import java.util.Set;

public class RepeatedFieldTypes implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META =
      new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private List<String> as_list;

  private Set<String> as_set;

  private Collection<String> as_collection;

  public RepeatedFieldTypes() {}

  public RepeatedFieldTypes(
      List<String> as_list, Set<String> as_set, Collection<String> as_collection) {
    this.as_list = as_list;
    this.as_set = as_set;
    this.as_collection = as_collection;
  }

  public List<String> getAs_list() {
    return this.as_list;
  }

  public RepeatedFieldTypes setAs_list(List<String> as_list) {
    this.as_list = as_list;
    return this;
  }

  public Set<String> getAs_set() {
    return this.as_set;
  }

  public RepeatedFieldTypes setAs_set(Set<String> as_set) {
    this.as_set = as_set;
    return this;
  }

  public Collection<String> getAs_collection() {
    return this.as_collection;
  }

  public RepeatedFieldTypes setAs_collection(Collection<String> as_collection) {
    this.as_collection = as_collection;
    return this;
  }
}
