// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericJsDts.proto

package constant.tsnumericjsdts;

public interface FooNames {
  String a = "a";
  String b = "b";
  String c = "c";
}
