// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// MapValueJsDts.proto

import io.github.jinganix.webpb.runtime.enumeration.Enumeration;

public enum Baz implements Enumeration<Integer> {
  x(0),
  y(1);

  private Integer value;

  Baz(Integer value) {
    this.value = value;
  }

  public static Baz fromValue(Integer value) {
    switch (value) {
      case 0:
        return x;
      case 1:
        return y;
      default:
        return null;
    }
  }

  @Override
  public Integer getValue() {
    return this.value;
  }
}
