// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// MapValueJsDts.proto

import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;
import java.util.Map;

public class MapValueJsDtsPb implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META =
      new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private Map<String, Baz> sort;

  public MapValueJsDtsPb() {}

  public MapValueJsDtsPb(Map<String, Baz> sort) {
    this.sort = sort;
  }

  public Map<String, Baz> getSort() {
    return this.sort;
  }

  public MapValueJsDtsPb setSort(Map<String, Baz> sort) {
    this.sort = sort;
    return this;
  }
}
