// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// EnumToString.proto

package webpbpb

type Test int32

const (
	Test_DEFAULT Test = 0
	Test_OTHER   Test = 100
)

var TestNames = map[Test]string{
	Test_DEFAULT: "DEFAULT",
	Test_OTHER:   "OTHER",
}

func (x Test) String() string {
	if name, ok := TestNames[x]; ok {
		return name
	}
	return ""
}
