// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// FieldInt64AsString.proto

package webpbpb

const (
	Test9Class   = "Test9"
	Test9Method  = ""
	Test9Context = ""
)

type Test9 struct {
	Test1 *int64 `webpb:"test1" json:"test1"`
}

func NewTest9() *Test9 {
	return &Test9{}
}

func (m *Test9) WebpbClass() string   { return Test9Class }
func (m *Test9) WebpbMethod() string  { return Test9Method }
func (m *Test9) WebpbContext() string { return Test9Context }
func (m *Test9) WebpbPath() string    { return "" }
