// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// HttpMethods.proto

package webpbpb

import (
	"fmt"
)

const (
	PostRequestClass   = "PostRequest"
	PostRequestMethod  = "POST"
	PostRequestContext = "api"
)

type PostRequest struct {
	Id   *int32  `webpb:"id" json:"id"`
	Body *string `webpb:"body" json:"body"`
}

func NewPostRequest() *PostRequest {
	return &PostRequest{}
}

func (m *PostRequest) WebpbClass() string   { return PostRequestClass }
func (m *PostRequest) WebpbMethod() string  { return PostRequestMethod }
func (m *PostRequest) WebpbContext() string { return PostRequestContext }
func (m *PostRequest) WebpbPath() string    { return fmt.Sprintf("/items/%v", m.Id) }

const (
	PutRequestClass   = "PutRequest"
	PutRequestMethod  = "PUT"
	PutRequestContext = "api"
)

type PutRequest struct {
	Id   *int32  `webpb:"id" json:"id"`
	Body *string `webpb:"body" json:"body"`
}

func NewPutRequest() *PutRequest {
	return &PutRequest{}
}

func (m *PutRequest) WebpbClass() string   { return PutRequestClass }
func (m *PutRequest) WebpbMethod() string  { return PutRequestMethod }
func (m *PutRequest) WebpbContext() string { return PutRequestContext }
func (m *PutRequest) WebpbPath() string    { return fmt.Sprintf("/items/%v", m.Id) }

const (
	DeleteRequestClass   = "DeleteRequest"
	DeleteRequestMethod  = "DELETE"
	DeleteRequestContext = "api"
)

type DeleteRequest struct {
	Id *int32 `webpb:"id" json:"id"`
}

func NewDeleteRequest() *DeleteRequest {
	return &DeleteRequest{}
}

func (m *DeleteRequest) WebpbClass() string   { return DeleteRequestClass }
func (m *DeleteRequest) WebpbMethod() string  { return DeleteRequestMethod }
func (m *DeleteRequest) WebpbContext() string { return DeleteRequestContext }
func (m *DeleteRequest) WebpbPath() string    { return fmt.Sprintf("/items/%v", m.Id) }
