// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// PrimitiveTypes.proto

package webpbpb

const (
	PrimitiveTypesClass   = "PrimitiveTypes"
	PrimitiveTypesMethod  = ""
	PrimitiveTypesContext = ""
)

type PrimitiveTypes struct {
	FloatField    *float32  `webpb:"float_field" json:"float_field"`
	DoubleField   *float64  `webpb:"double_field" json:"double_field"`
	Uint32Field   *uint32   `webpb:"uint32_field" json:"uint32_field"`
	Uint64Field   *uint64   `webpb:"uint64_field" json:"uint64_field"`
	Sint32Field   *int32    `webpb:"sint32_field" json:"sint32_field"`
	Sint64Field   *int64    `webpb:"sint64_field" json:"sint64_field"`
	Fixed32Field  *uint32   `webpb:"fixed32_field" json:"fixed32_field"`
	Fixed64Field  *uint64   `webpb:"fixed64_field" json:"fixed64_field"`
	Sfixed32Field *int32    `webpb:"sfixed32_field" json:"sfixed32_field"`
	Sfixed64Field *int64    `webpb:"sfixed64_field" json:"sfixed64_field"`
	RepeatedFloat []float32 `webpb:"repeated_float" json:"repeated_float"`
}

func NewPrimitiveTypes() *PrimitiveTypes {
	return &PrimitiveTypes{}
}

func (m *PrimitiveTypes) WebpbClass() string   { return PrimitiveTypesClass }
func (m *PrimitiveTypes) WebpbMethod() string  { return PrimitiveTypesMethod }
func (m *PrimitiveTypes) WebpbContext() string { return PrimitiveTypesContext }
func (m *PrimitiveTypes) WebpbPath() string    { return "" }
