// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// RecursiveMessage.proto

package webpbpb

const (
	Test11Class   = "Test11"
	Test11Method  = ""
	Test11Context = ""
)

type Test11 struct {
	Test1  *int32  `webpb:"test1" json:"test1"`
	Test11 *Test11 `webpb:"test11" json:"test11"`
}

func NewTest11() *Test11 {
	return &Test11{}
}

func (m *Test11) WebpbClass() string   { return Test11Class }
func (m *Test11) WebpbMethod() string  { return Test11Method }
func (m *Test11) WebpbContext() string { return Test11Context }
func (m *Test11) WebpbPath() string    { return "" }
