// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// RepeatedFieldTypes.proto

package webpbpb

const (
	RepeatedFieldTypesClass   = "RepeatedFieldTypes"
	RepeatedFieldTypesMethod  = ""
	RepeatedFieldTypesContext = ""
)

type RepeatedFieldTypes struct {
	AsList       []string `webpb:"as_list" json:"as_list"`
	AsSet        []string `webpb:"as_set" json:"as_set"`
	AsCollection []string `webpb:"as_collection" json:"as_collection"`
}

func NewRepeatedFieldTypes() *RepeatedFieldTypes {
	return &RepeatedFieldTypes{}
}

func (m *RepeatedFieldTypes) WebpbClass() string   { return RepeatedFieldTypesClass }
func (m *RepeatedFieldTypes) WebpbMethod() string  { return RepeatedFieldTypesMethod }
func (m *RepeatedFieldTypes) WebpbContext() string { return RepeatedFieldTypesContext }
func (m *RepeatedFieldTypes) WebpbPath() string    { return "" }
