// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// FieldLevel.proto

package webpbpb

const (
	Level3Class   = "Level3"
	Level3Method  = ""
	Level3Context = ""
)

type Level3 struct {
	Test1 *int32 `webpb:"test1" json:"test1"`
}

func NewLevel3() *Level3 {
	return &Level3{}
}

func (m *Level3) WebpbClass() string   { return Level3Class }
func (m *Level3) WebpbMethod() string  { return Level3Method }
func (m *Level3) WebpbContext() string { return Level3Context }
func (m *Level3) WebpbPath() string    { return "" }

const (
	Level2Class   = "Level2"
	Level2Method  = ""
	Level2Context = ""
)

type Level2 struct {
	Test1 *int32    `webpb:"test1" json:"test1"`
	Test2 *Level3   `webpb:"test2" json:"test2"`
	Test3 []*Level3 `webpb:"test3" json:"test3"`
}

func NewLevel2() *Level2 {
	return &Level2{}
}

func (m *Level2) WebpbClass() string   { return Level2Class }
func (m *Level2) WebpbMethod() string  { return Level2Method }
func (m *Level2) WebpbContext() string { return Level2Context }
func (m *Level2) WebpbPath() string    { return "" }

const (
	Level1Class   = "Level1"
	Level1Method  = ""
	Level1Context = ""
)

type Level1 struct {
	Test1 *int32             `webpb:"test1" json:"test1"`
	Test2 *Level2            `webpb:"test2" json:"test2"`
	Test3 []*Level2          `webpb:"test3" json:"test3"`
	Test4 *Level3            `webpb:"test4" json:"test4"`
	Test5 map[int32]*Level3  `webpb:"test5" json:"test5"`
	Test6 map[string]*Level3 `webpb:"test6" json:"test6"`
}

func NewLevel1() *Level1 {
	return &Level1{}
}

func (m *Level1) WebpbClass() string   { return Level1Class }
func (m *Level1) WebpbMethod() string  { return Level1Method }
func (m *Level1) WebpbContext() string { return Level1Context }
func (m *Level1) WebpbPath() string    { return "" }
