// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Include.proto

package include;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Message implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META = new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private Integer id;

  public Message() {
  }

  public Message(Integer id) {
    this.id = id;
  }

  @JsonIgnoreProperties(ignoreUnknown = true)
  public static class Nested implements WebpbMessage {

    public static final String WEBPB_METHOD = "";

    public static final String WEBPB_CONTEXT = "";

    public static final String WEBPB_PATH = "";

    public static final WebpbMeta WEBPB_META = new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

    @Override
    public WebpbMeta webpbMeta() {
      return WEBPB_META;
    }

    private Integer test1;

    public Nested() {
    }

    public Nested(Integer test1) {
      this.test1 = test1;
    }
  }
}
