// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// BazEnumJsDts.proto

package constant.bazenum;

public interface BazNames {
  String a = "a";
  String b = "b";
  String c = "c";
}
