// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// BarEnumTsAndJs.proto

export const enum Bar {
  a = 0,
  b = 1,
  c = 2,
}

export declare const BarValues: readonly Bar[];
