// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// MapValueJsDts.proto

export const enum Baz {
  x = 0,
  y = 1,
}

export declare const BazValues: readonly Baz[];
