// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// EnumDefaultConst.proto

export const enum ConstEnum4 {
  DEFAULT = 0,
  OTHER = 1,
}

export const ConstEnum4Values = [ConstEnum4.DEFAULT, ConstEnum4.OTHER];

export enum EnumConstEnum4 {
  DEFAULT = 0,
  OTHER = 1,
}

export const EnumConstEnum4Values = [
  EnumConstEnum4.DEFAULT,
  EnumConstEnum4.OTHER,
];
