// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// MapValueJsDts.proto

import * as Webpb from "webpb";

export type { Baz } from "./Baz";

export { BazValues } from "./Baz.js";

export interface IMapValueJsDtsPb {
  sort: Record<string, Baz>;
}

export class MapValueJsDtsPb implements IMapValueJsDtsPb, Webpb.WebpbMessage {
  sort!: Record<string, Baz>;
  webpbMeta: () => Webpb.WebpbMeta;

  static CLASS = "MapValueJsDtsPb";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IMapValueJsDtsPb) {
    Webpb.assign(p, this, []);
    this.webpbMeta = () =>
      ({
        class: "MapValueJsDtsPb",
        context: "",
        method: "",
        path: "",
      }) as Webpb.WebpbMeta;
  }

  static create(p?: IMapValueJsDtsPb): MapValueJsDtsPb {
    return new MapValueJsDtsPb(p);
  }

  static fromAlias(data?: unknown): MapValueJsDtsPb {
    return MapValueJsDtsPb.create(data as IMapValueJsDtsPb);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
