// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericDebugEnum.proto

export enum LogLevel {
  info = 0,
  warn = 1,
  error = 2,
}

export const LogLevelValues: readonly LogLevel[] = [0, 1, 2];

export const LogLevelByName = {
  error: 2,
  info: 0,
  warn: 1,
} as const;

export type LogLevelName = keyof typeof LogLevelByName;

export const LogLevelByValue = {
  0: "info",
  1: "warn",
  2: "error",
} as const;

export type LogLevelByValueKey = keyof typeof LogLevelByValue;
