// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericEnum.proto

export const enum ClaimStatus {
  acceptable = 0,
  active = 1,
  claimable = 2,
}

export const ClaimStatusValues = [0, 1, 2];

export const ClaimStatusByName = {
  acceptable: 0,
  active: 1,
  claimable: 2,
};
