// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericEnum.proto

export const enum ClaimStatus {
  acceptable = 0,
  active = 1,
  claimable = 2,
}

export const ClaimStatusValues: readonly ClaimStatus[] = [0, 1, 2];

export const ClaimStatusByName = {
  acceptable: 0,
  active: 1,
  claimable: 2,
} as const;

export type ClaimStatusName = keyof typeof ClaimStatusByName;

export function claimStatusFromName(name: ClaimStatusName): ClaimStatus {
  return ClaimStatusByName[name];
}
