// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsStringValuesEnum.proto

export const enum TokenType {
  BEARER = "Bearer",
  ACCESS = "Access",
}

export const TokenTypeValues: readonly TokenType[] = [
  "Bearer" as TokenType,
  "Access" as TokenType,
];

export enum EnumTokenType {
  BEARER = "Bearer",
  ACCESS = "Access",
}

export const EnumTokenTypeValues: readonly EnumTokenType[] = [
  "Bearer" as EnumTokenType,
  "Access" as EnumTokenType,
];

export const TokenTypeByName = {
  ACCESS: "Access",
  BEARER: "Bearer",
} as const;

export type TokenTypeName = keyof typeof TokenTypeByName;

export function tokenTypeFromName(name: TokenTypeName): TokenType {
  return TokenTypeByName[name];
}
