// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// EnumDefaultConst.proto

package constant.enum4;

public interface ConstEnum4Names {
  String DEFAULT = "DEFAULT";
  String OTHER = "OTHER";
}
