// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// EnumDefaultConst.proto

package constant.enum4;

import io.github.jinganix.webpb.runtime.enumeration.Enumeration;

public enum ConstEnum4 implements Enumeration<Integer> {
  DEFAULT(0),
  OTHER(1);

  private Integer value;

  ConstEnum4(Integer value) {
    this.value = value;
  }

  public static ConstEnum4 fromValue(Integer value) {
    switch (value) {
      case 0:
        return DEFAULT;
      case 1:
        return OTHER;
      default:
        return null;
    }
  }

  @Override
  public Integer getValue() {
    return this.value;
  }
}
