// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// RepeatedEnum.proto

package repeated_enum;

import io.github.jinganix.webpb.runtime.enumeration.Enumeration;

public enum Status implements Enumeration<Integer> {
  ACTIVE(0),
  INACTIVE(1);

  private Integer value;

  Status(Integer value) {
    this.value = value;
  }

  public static Status fromValue(Integer value) {
    switch (value) {
      case 0:
        return ACTIVE;
      case 1:
        return INACTIVE;
      default:
        return null;
    }
  }

  @Override
  public Integer getValue() {
    return this.value;
  }
}
