// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// RepeatedEnum.proto

package repeated_enum;

public interface StatusNames {
  String ACTIVE = "ACTIVE";
  String INACTIVE = "INACTIVE";
}
