// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// BazEnumJsDts.proto

package constant.bazenum;

public interface BazValues {
  int a = 0;
  int b = 1;
  int c = 2;
}
