package core

// Shared constants for webpb code generation.
const (
	Header          = "Code generated by Webpb compiler, do not edit."
	GitURL          = "https://github.com/jinganix/webpb"
	WebpbExtend     = "WebpbExtend.proto"
	WebpbOptions    = "(.*/)?((?i)webpb[\\._-]?options\\.proto)"
	RuntimePackage  = "io.github.jinganix.webpb.runtime"
)
