// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Test.proto

package test;

public interface Test5Names {
  String test5_1 = "test5_1";
  String test5_2 = "test5_2";
  String test5_3 = "test5_3";
}
