// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Test.proto

package test;

public interface Test5Values {
  String test5_1 = "text1";
  String test5_2 = "text2";
  String test5_3 = "test5_3";
}
