// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Test.proto

package test;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;
import java.util.Map;
import test.message.AbstractClass;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Test2 extends AbstractClass implements WebpbMessage {

  public static final String WEBPB_METHOD = "GET";

  public static final String WEBPB_CONTEXT = "/test";

  public static final String WEBPB_PATH = "/test/{test2}?id={test1}&data1={test3.test1}&data2={test3.test2}";

  public static final WebpbMeta WEBPB_META = new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private Long test1;

  private String test2;

  private Test6 test3;

  private Map<Integer, Test1> test4;

  public Test2() {
  }

  public Test2(Long test1, String test2, Test6 test3, Map<Integer, Test1> test4) {
    this.test1 = test1;
    this.test2 = test2;
    this.test3 = test3;
    this.test4 = test4;
  }
}
