// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Test.proto

package test;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.github.jinganix.webpb.runtime.enumeration.Enumeration;

@JsonIgnoreProperties(ignoreUnknown = true)
public enum Test3 implements Enumeration<String> {

  test3_1("test3_1"),
  test3_2("test3_2"),
  test3_3("test3_3");

  private String value;

  Test3(String value) {
    this.value = value;
  }

  public static Test3 fromValue(String value) {
    switch (value) {
    case "test3_1":
      return test3_1;
    case "test3_2":
      return test3_2;
    case "test3_3":
      return test3_3;
    default:
      return null;
    }
  }

  @Override
  public String getValue() {
    return this.value;
  }
}
