// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// FooBarJsDts.proto

package constant.fooproto;

import constant.barenum.Bar;
import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;

public class FooBarPb implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META =
      new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private Bar type;

  public FooBarPb() {}

  public FooBarPb(Bar type) {
    this.type = type;
  }

  public Bar getType() {
    return this.type;
  }

  public FooBarPb setType(Bar type) {
    this.type = type;
    return this;
  }
}
