// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// ConstEnum1.proto

package constant.enum1;

import io.github.jinganix.webpb.runtime.enumeration.Enumeration;

public enum ConstEnum1 implements Enumeration<Integer> {

  DEFAULT(0);

  private Integer value;

  ConstEnum1(Integer value) {
    this.value = value;
  }

  public static ConstEnum1 fromValue(Integer value) {
    switch (value) {
    case 0:
      return DEFAULT;
    default:
      return null;
    }
  }

  @Override
  public Integer getValue() {
    return this.value;
  }
}
