// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// include/Extends.proto

import * as Webpb from "webpb";

export interface IExtends {
  foo_1: number;
  bar_1: string;
}

export class Extends implements IExtends, Webpb.WebpbMessage {
  foo_1!: number;
  bar_1!: string;
  webpbMeta: () => Webpb.WebpbMeta;

  protected constructor(p?: IExtends) {
    Webpb.assign(p, this, []);
    this.webpbMeta = () => (p && {
      class: "Extends",
      context: "",
      method: "",
      path: "",
    }) as Webpb.WebpbMeta;
  }

  static create(p: IExtends): Extends {
    return new Extends(p);
  }

  static fromAlias(data: Record<string, unknown>): Extends {
    return Extends.create(data as any);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
