// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb

export { ISubTypeSubValue1 } from "./SubTypeSubValueProto";
export { ISubTypeSubValue2 } from "./SubTypeSubValueProto";
export { ISubTypeSubValue4 } from "./SubTypeSubValueProto";
export { ISubTypeSubValue5 } from "./SubTypeSubValueProto";
export { ISubTypeSubValue6 } from "./SubTypeSubValueProto";
import * as SubTypeSubValueProto from "./SubTypeSubValueProto";

export type SubTypeSubValueSuperTypes =
  | SubTypeSubValueProto.ISubTypeSubValue1
  | SubTypeSubValueProto.ISubTypeSubValue2
  | SubTypeSubValueProto.ISubTypeSubValue4
  | SubTypeSubValueProto.ISubTypeSubValue5
  | SubTypeSubValueProto.ISubTypeSubValue6
;
