// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb

import * as SubTypeSubValueProto from "./SubTypeSubValueProto";

export type ISubTypeSubValue1 = SubTypeSubValueProto.ISubTypeSubValue1;
export type ISubTypeSubValue2 = SubTypeSubValueProto.ISubTypeSubValue2;
export type ISubTypeSubValue4 = SubTypeSubValueProto.ISubTypeSubValue4;
export type ISubTypeSubValue5 = SubTypeSubValueProto.ISubTypeSubValue5;
export type ISubTypeSubValue6 = SubTypeSubValueProto.ISubTypeSubValue6;

export type SubTypeSubValueSuperTypes =
  | ISubTypeSubValue1
  | ISubTypeSubValue2
  | ISubTypeSubValue4
  | ISubTypeSubValue5
  | ISubTypeSubValue6
;
