// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// EnumDefaultConst.proto

package constant.enum4;

public interface ConstEnum4Values {
  int DEFAULT = 0;
  int OTHER = 1;
}
