// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// AliasReserve.proto

package auto.alias.reserve;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;

public class AliasReserveParent implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META =
      new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  @JsonProperty("a")
  private Integer foo_1;

  public AliasReserveParent() {}

  public AliasReserveParent(Integer foo_1) {
    this.foo_1 = foo_1;
  }

  public Integer getFoo_1() {
    return this.foo_1;
  }

  public AliasReserveParent setFoo_1(Integer foo_1) {
    this.foo_1 = foo_1;
    return this;
  }
}
