// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// ${filename}

<#if package?has_content>package ${package};

</#if>
public interface ${className}Values {
<#list enums as enum>
  <#if valueType == 'Integer'>int<#else>${valueType}</#if> ${enum.name} = ${enum.value};
</#list>
}
