// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// ${filename}

<#if package?has_content>package ${package};

</#if>
public interface ${className}Names {
<#list enums as enum>
  String ${enum.name} = "${enum.name}";
</#list>
}
