// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// ${filename}

<#if package?has_content>package ${package};

</#if>
<#if imports??>
  <#list imports as import>
import ${import};
  </#list>
</#if>

<#if msgAnnos??>
  <#list msgAnnos as anno>
${anno}
  </#list>
</#if>
public class ${className}<#if extend??> extends ${extend}</#if ><#if implements?has_content> implements <#list implements as implement>${implement}<#sep>, </#sep></#list></#if> {

<#include "/message.body.ftl">
}
