// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsStringValuesEnum.proto

package constant.tsstringvalues;

public interface TokenTypeValues {
  String BEARER = "Bearer";
  String ACCESS = "Access";
}
