// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// MapValueTest.proto

import io.github.jinganix.webpb.runtime.enumeration.Enumeration;

public enum Direction implements Enumeration<Integer> {

  asc(0),
  desc(1);

  private Integer value;

  Direction(Integer value) {
    this.value = value;
  }

  public static Direction fromValue(Integer value) {
    switch (value) {
    case 0:
      return asc;
    case 1:
      return desc;
    default:
      return null;
    }
  }

  @Override
  public Integer getValue() {
    return this.value;
  }
}
