// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// AugmentStatus.proto

package augment.test.user;

public interface AugmentStatusNames {
  String AUGMENT_UNKNOWN = "AUGMENT_UNKNOWN";
  String AUGMENT_ACTIVE = "AUGMENT_ACTIVE";
}
