// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// AugmentStatus.proto

package augment.test.user;

public interface AugmentStatusValues {
  int AUGMENT_UNKNOWN = 0;
  int AUGMENT_ACTIVE = 1;
}
