// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// User.proto

package augment.test.user;

import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;

public class UserPb implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META =
      new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private Long id;

  private String username;

  private Long staffId;

  private String displayName;

  public UserPb() {}

  public UserPb(Long id, String username, Long staffId, String displayName) {
    this.id = id;
    this.username = username;
    this.staffId = staffId;
    this.displayName = displayName;
  }

  public Long getId() {
    return this.id;
  }

  public UserPb setId(Long id) {
    this.id = id;
    return this;
  }

  public String getUsername() {
    return this.username;
  }

  public UserPb setUsername(String username) {
    this.username = username;
    return this;
  }

  public Long getStaffId() {
    return this.staffId;
  }

  public UserPb setStaffId(Long staffId) {
    this.staffId = staffId;
    return this;
  }

  public String getDisplayName() {
    return this.displayName;
  }

  public UserPb setDisplayName(String displayName) {
    this.displayName = displayName;
    return this;
  }
}
