// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// User.proto

package augment.test.user;

import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;
import java.util.List;

public class UserDetailsPb extends UserPb implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META =
      new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private List<Long> roleIds;

  public UserDetailsPb() {}

  public UserDetailsPb(List<Long> roleIds) {
    this.roleIds = roleIds;
  }

  public List<Long> getRoleIds() {
    return this.roleIds;
  }

  public UserDetailsPb setRoleIds(List<Long> roleIds) {
    this.roleIds = roleIds;
    return this;
  }
}
