// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// ExtendsEmptyPackage.proto

package webpbpb

const (
	ImportTestClass   = "ImportTest"
	ImportTestMethod  = ""
	ImportTestContext = ""
)

type ImportTest struct {
	Foo1      int32          `webpb:"foo_1" json:"foo_1"`
	Bar1      string         `webpb:"bar_1" json:"bar_1"`
	Test      *NoPackageTest `webpb:"test" json:"test"`
	Foo2      int32          `webpb:"foo_2" json:"foo_2"`
	Bar2      string         `webpb:"bar_2" json:"bar_2"`
	NoPackage *NoPackage     `webpb:"no_package" json:"no_package"`
}

func NewImportTest() *ImportTest {
	return &ImportTest{}
}

func (m *ImportTest) WebpbClass() string   { return ImportTestClass }
func (m *ImportTest) WebpbMethod() string  { return ImportTestMethod }
func (m *ImportTest) WebpbContext() string { return ImportTestContext }
func (m *ImportTest) WebpbPath() string    { return "" }
