// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// HttpMethods.proto

package http;

import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;

public class DeleteRequest implements WebpbMessage {

  public static final String WEBPB_METHOD = "DELETE";

  public static final String WEBPB_CONTEXT = "/api";

  public static final String WEBPB_PATH = "/items/{id}";

  public static final WebpbMeta WEBPB_META =
      new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private Integer id;

  public DeleteRequest() {}

  public DeleteRequest(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return this.id;
  }

  public DeleteRequest setId(Integer id) {
    this.id = id;
    return this;
  }
}
