// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// HttpMethods.proto

package http;

import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;

public class PostRequest implements WebpbMessage {

  public static final String WEBPB_METHOD = "POST";

  public static final String WEBPB_CONTEXT = "/api";

  public static final String WEBPB_PATH = "/items/{id}";

  public static final WebpbMeta WEBPB_META =
      new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private Integer id;

  private String body;

  public PostRequest() {}

  public PostRequest(Integer id, String body) {
    this.id = id;
    this.body = body;
  }

  public Integer getId() {
    return this.id;
  }

  public PostRequest setId(Integer id) {
    this.id = id;
    return this;
  }

  public String getBody() {
    return this.body;
  }

  public PostRequest setBody(String body) {
    this.body = body;
    return this;
  }
}
