// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// User.proto

import * as Webpb from "webpb";
import * as UserAugmentProto from "./UserAugmentProto";

export interface IUserPb {
  id: number;
  username: string;
  staffId?: number | null;
  displayName?: string | null;
}

export class UserPb implements IUserPb, Webpb.WebpbMessage {
  id!: number;
  username!: string;
  staffId?: number | null;
  displayName?: string | null;
  webpbMeta: () => Webpb.WebpbMeta;

  static CLASS = "UserPb";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IUserPb) {
    Webpb.assign(p, this, []);
    this.webpbMeta = () =>
      ({
        class: "UserPb",
        context: "",
        method: "",
        path: "",
      }) as Webpb.WebpbMeta;
  }

  static create(p?: IUserPb): UserPb {
    return new UserPb(p);
  }

  static fromAlias(data?: unknown): UserPb {
    return UserPb.create(data as IUserPb);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}

export interface IUserDetailsPb extends UserAugmentProto.IUserPb {
  roleIds: number[];
}

export class UserDetailsPb
  extends UserAugmentProto.UserPb
  implements IUserDetailsPb, Webpb.WebpbMessage
{
  roleIds!: number[];
  webpbMeta: () => Webpb.WebpbMeta;

  static CLASS = "UserDetailsPb";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IUserDetailsPb) {
    super();
    Webpb.assign(p, this, []);
    this.webpbMeta = () =>
      ({
        class: "UserDetailsPb",
        context: "",
        method: "",
        path: "",
      }) as Webpb.WebpbMeta;
  }

  static create(p?: IUserDetailsPb): UserDetailsPb {
    return new UserDetailsPb(p);
  }

  static fromAlias(data?: unknown): UserDetailsPb {
    return UserDetailsPb.create(data as IUserDetailsPb);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
