// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// BarEnumShim.proto

package constant.barenum;

import io.github.jinganix.webpb.runtime.enumeration.Enumeration;

public enum Bar implements Enumeration<Integer> {
  a(0),
  b(1),
  c(2);

  private Integer value;

  Bar(Integer value) {
    this.value = value;
  }

  public static Bar fromValue(Integer value) {
    switch (value) {
      case 0:
        return a;
      case 1:
        return b;
      case 2:
        return c;
      default:
        return null;
    }
  }

  @Override
  public Integer getValue() {
    return this.value;
  }
}
