// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// AliasSkip.proto

package webpbpb

const (
	AliasSkipClass   = "AliasSkip"
	AliasSkipMethod  = ""
	AliasSkipContext = ""
)

type AliasSkip struct {
	B int32 `webpb:"b" json:"b"`
	A int32 `webpb:"a" json:"a"`
}

func NewAliasSkip() *AliasSkip {
	return &AliasSkip{}
}

func (m *AliasSkip) WebpbClass() string   { return AliasSkipClass }
func (m *AliasSkip) WebpbMethod() string  { return AliasSkipMethod }
func (m *AliasSkip) WebpbContext() string { return AliasSkipContext }
func (m *AliasSkip) WebpbPath() string    { return "" }
