// Package webpb is the Go runtime for code generated by webpb. It converts
// generated messages to and from the alias-keyed representation used on the
// wire (see toWebpbAlias/fromAlias in the TypeScript and Java runtimes).
package webpb

import (
	"encoding/base64"
	"fmt"
	"reflect"
	"strconv"
	"strings"
)

// Message is implemented by every generated Go message.
type Message interface {
	WebpbClass() string
	WebpbContext() string
	WebpbMethod() string
	WebpbPath() string
}

// Meta describes where a message is routed.
type Meta struct {
	Class   string
	Context string
	Method  string
	Path    string
}

// Of returns the routing metadata of a generated message.
func Of(message Message) Meta {
	return Meta{
		Class:   message.WebpbClass(),
		Context: message.WebpbContext(),
		Method:  message.WebpbMethod(),
		Path:    message.WebpbPath(),
	}
}

// ToAlias converts a generated message into its alias-keyed wire form.
func ToAlias(message Message) map[string]any {
	value := reflect.ValueOf(message)
	if value.Kind() == reflect.Pointer {
		if value.IsNil() {
			return nil
		}
		value = value.Elem()
	}
	if value.Kind() != reflect.Struct {
		return nil
	}
	return structToAlias(value)
}

func structToAlias(value reflect.Value) map[string]any {
	typ := value.Type()
	out := make(map[string]any, typ.NumField())
	for i := 0; i < typ.NumField(); i++ {
		key, ok := aliasKey(typ.Field(i))
		if !ok {
			continue
		}
		field := value.Field(i)
		if isUnset(field) {
			continue
		}
		out[key] = toAliasValue(field)
	}
	return out
}

// isUnset reports whether an optional value carries no presence, matching the
// TypeScript runtime where unset fields are omitted from the wire form.
func isUnset(value reflect.Value) bool {
	switch value.Kind() {
	case reflect.Pointer, reflect.Interface, reflect.Map, reflect.Slice:
		return value.IsNil()
	default:
		return false
	}
}

func toAliasValue(value reflect.Value) any {
	if !value.IsValid() {
		return nil
	}
	switch value.Kind() {
	case reflect.Pointer, reflect.Interface:
		if value.IsNil() {
			return nil
		}
		elem := value.Elem()
		if message, ok := value.Interface().(Message); ok {
			return ToAlias(message)
		}
		return toAliasValue(elem)
	case reflect.Slice:
		if value.IsNil() {
			return nil
		}
		if value.Type().Elem().Kind() == reflect.Uint8 {
			return value.Interface()
		}
		out := make([]any, value.Len())
		for i := 0; i < value.Len(); i++ {
			out[i] = toAliasValue(value.Index(i))
		}
		return out
	case reflect.Map:
		if value.IsNil() {
			return nil
		}
		if value.Type().Key().Kind() == reflect.String {
			out := make(map[string]any, value.Len())
			for _, key := range value.MapKeys() {
				out[key.String()] = toAliasValue(value.MapIndex(key))
			}
			return out
		}
		out := make(map[any]any, value.Len())
		for _, key := range value.MapKeys() {
			out[key.Interface()] = toAliasValue(value.MapIndex(key))
		}
		return out
	case reflect.Struct:
		if message, ok := value.Interface().(Message); ok {
			return ToAlias(message)
		}
		return value.Interface()
	default:
		return value.Interface()
	}
}

// Populate fills a generated message from its alias-keyed wire form. Pass a
// message created by the generated New* constructor so proto2 defaults apply;
// only keys present in data overwrite the current values.
func Populate(data map[string]any, message Message) error {
	if data == nil {
		return nil
	}
	value := reflect.ValueOf(message)
	if value.Kind() != reflect.Pointer || value.IsNil() {
		return fmt.Errorf("webpb: Populate requires a non-nil pointer to a message")
	}
	return populateStruct(data, value.Elem())
}

func populateStruct(data map[string]any, value reflect.Value) error {
	typ := value.Type()
	index := map[string]int{}
	for i := 0; i < typ.NumField(); i++ {
		if key, ok := aliasKey(typ.Field(i)); ok {
			index[key] = i
		}
	}
	for key, raw := range data {
		if raw == nil {
			continue
		}
		i, ok := index[key]
		if !ok {
			continue
		}
		if err := setValue(value.Field(i), raw); err != nil {
			return fmt.Errorf("webpb: field %s.%s: %w", typ.Name(), typ.Field(i).Name, err)
		}
	}
	return nil
}

func setValue(field reflect.Value, raw any) error {
	if message, ok := raw.(Message); ok {
		return setMessage(field, message)
	}
	switch field.Kind() {
	case reflect.Pointer:
		if field.IsNil() {
			field.Set(reflect.New(field.Type().Elem()))
		}
		return setValue(field.Elem(), raw)
	case reflect.Struct:
		nested, ok := raw.(map[string]any)
		if !ok {
			return fmt.Errorf("expected object, got %T", raw)
		}
		return populateStruct(nested, field)
	case reflect.Slice:
		if field.Type().Elem().Kind() == reflect.Uint8 {
			bytes, err := toBytes(raw)
			if err != nil {
				return err
			}
			field.SetBytes(bytes)
			return nil
		}
		items, ok := raw.([]any)
		if !ok {
			return fmt.Errorf("expected array, got %T", raw)
		}
		slice := reflect.MakeSlice(field.Type(), len(items), len(items))
		for i, item := range items {
			if err := setValue(slice.Index(i), item); err != nil {
				return err
			}
		}
		field.Set(slice)
		return nil
	case reflect.Map:
		record, ok := raw.(map[string]any)
		if !ok {
			return fmt.Errorf("expected object, got %T", raw)
		}
		out := reflect.MakeMapWithSize(field.Type(), len(record))
		for key, item := range record {
			mapValue := reflect.New(field.Type().Elem()).Elem()
			if err := setValue(mapValue, item); err != nil {
				return err
			}
			out.SetMapIndex(reflect.ValueOf(key).Convert(field.Type().Key()), mapValue)
		}
		field.Set(out)
		return nil
	case reflect.String:
		value, err := toString(raw)
		if err != nil {
			return err
		}
		field.SetString(value)
		return nil
	case reflect.Bool:
		value, err := toBool(raw)
		if err != nil {
			return err
		}
		field.SetBool(value)
		return nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		value, err := toInt64(raw)
		if err != nil {
			return err
		}
		field.SetInt(value)
		return nil
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		value, err := toUint64(raw)
		if err != nil {
			return err
		}
		field.SetUint(value)
		return nil
	case reflect.Float32, reflect.Float64:
		value, err := toFloat64(raw)
		if err != nil {
			return err
		}
		field.SetFloat(value)
		return nil
	default:
		if field.CanSet() && reflect.TypeOf(raw) == field.Type() {
			field.Set(reflect.ValueOf(raw))
			return nil
		}
		return fmt.Errorf("unsupported kind %s", field.Kind())
	}
}

func setMessage(field reflect.Value, message Message) error {
	value := reflect.ValueOf(message)
	switch field.Kind() {
	case reflect.Pointer:
		if field.Type() == value.Type() {
			field.Set(value)
			return nil
		}
		if field.IsNil() {
			field.Set(reflect.New(field.Type().Elem()))
		}
		return populateStruct(ToAlias(message), field.Elem())
	case reflect.Struct:
		if field.Type() == value.Elem().Type() {
			field.Set(value.Elem())
			return nil
		}
		return populateStruct(ToAlias(message), field)
	default:
		return fmt.Errorf("unsupported message target %s", field.Kind())
	}
}

// Query renders query parameters, matching the TypeScript runtime semantics.
func Query(pre string, params map[string]any) string {
	queries := make([]string, 0, len(params))
	push := func(key, value string) {
		if key != "" && value != "" {
			queries = append(queries, key+"="+urlEncode(value))
		}
	}
	for key, value := range params {
		if value == nil {
			continue
		}
		switch typed := value.(type) {
		case []string:
			if len(typed) > 0 {
				push(key, strings.Join(typed, ","))
			}
		case map[string]string:
			for mapKey, mapValue := range typed {
				if mapValue == "" {
					push(key, mapKey)
				} else {
					push(key, mapKey+","+mapValue)
				}
			}
		default:
			push(key, fmt.Sprint(value))
		}
	}
	if len(queries) == 0 {
		return ""
	}
	return pre + strings.Join(queries, "&")
}

// Getter reads a dotted path from a nested object, returning nil when absent.
func Getter(data any, path string) any {
	current := data
	for _, key := range strings.Split(path, ".") {
		if key == "" {
			continue
		}
		record, ok := current.(map[string]any)
		if !ok {
			return nil
		}
		current = record[key]
	}
	return current
}

// MapValues applies mapping to every value of a string-keyed record.
func MapValues(record map[string]any, mapping func(any) any) map[string]any {
	out := make(map[string]any, len(record))
	for key, value := range record {
		out[key] = mapping(value)
	}
	return out
}

func aliasKey(field reflect.StructField) (string, bool) {
	if key, ok := field.Tag.Lookup("webpb"); ok && key != "" {
		return key, true
	}
	if key, ok := field.Tag.Lookup("json"); ok && key != "" {
		return strings.Split(key, ",")[0], true
	}
	return "", false
}

func toString(raw any) (string, error) {
	if value, ok := raw.(string); ok {
		return value, nil
	}
	if value, ok := raw.([]byte); ok {
		return string(value), nil
	}
	if value, ok := raw.(fmt.Stringer); ok {
		return value.String(), nil
	}
	value := reflect.ValueOf(raw)
	if value.Kind() == reflect.String {
		return value.String(), nil
	}
	return "", fmt.Errorf("expected string, got %T", raw)
}

func toBool(raw any) (bool, error) {
	if value, ok := raw.(bool); ok {
		return value, nil
	}
	if value, ok := raw.(string); ok {
		return strconv.ParseBool(value)
	}
	return false, fmt.Errorf("expected bool, got %T", raw)
}

func toInt64(raw any) (int64, error) {
	if value, ok := raw.(string); ok {
		return strconv.ParseInt(value, 10, 64)
	}
	switch value := reflect.ValueOf(raw); value.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return value.Int(), nil
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return int64(value.Uint()), nil
	case reflect.Float32, reflect.Float64:
		return int64(value.Float()), nil
	default:
		return 0, fmt.Errorf("expected integer, got %T", raw)
	}
}

func toUint64(raw any) (uint64, error) {
	if value, ok := raw.(string); ok {
		return strconv.ParseUint(value, 10, 64)
	}
	switch value := reflect.ValueOf(raw); value.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return uint64(value.Int()), nil
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return value.Uint(), nil
	case reflect.Float32, reflect.Float64:
		return uint64(value.Float()), nil
	default:
		return 0, fmt.Errorf("expected unsigned integer, got %T", raw)
	}
}

func toFloat64(raw any) (float64, error) {
	if value, ok := raw.(string); ok {
		return strconv.ParseFloat(value, 64)
	}
	switch value := reflect.ValueOf(raw); value.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return float64(value.Int()), nil
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return float64(value.Uint()), nil
	case reflect.Float32, reflect.Float64:
		return value.Float(), nil
	default:
		return 0, fmt.Errorf("expected number, got %T", raw)
	}
}

func toBytes(raw any) ([]byte, error) {
	switch value := raw.(type) {
	case []byte:
		return value, nil
	case string:
		if decoded, err := base64.StdEncoding.DecodeString(value); err == nil {
			return decoded, nil
		}
		return []byte(value), nil
	default:
		return nil, fmt.Errorf("expected bytes, got %T", raw)
	}
}

// urlEncode matches JavaScript encodeURIComponent, which the TypeScript
// runtime uses for query values.
func urlEncode(value string) string {
	var b strings.Builder
	for i := 0; i < len(value); i++ {
		c := value[i]
		switch {
		case c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' || c >= '0' && c <= '9',
			c == '-' || c == '_' || c == '.' || c == '~' || c == '!',
			c == '\'' || c == '(' || c == ')' || c == '*':
			b.WriteByte(c)
		default:
			b.WriteString(fmt.Sprintf("%%%02X", c))
		}
	}
	return b.String()
}

// SubTypeFactory builds a concrete message from its alias form.
type SubTypeFactory func(data map[string]any) (Message, error)

// SubTypeRegistry maps a base message class plus discriminator value to a
// concrete message factory (webpb sub_type/sub_values).
type SubTypeRegistry struct {
	entries map[string]map[string]SubTypeFactory
}

// NewSubTypeRegistry creates an empty registry.
func NewSubTypeRegistry() *SubTypeRegistry {
	return &SubTypeRegistry{entries: map[string]map[string]SubTypeFactory{}}
}

// Register adds a factory for base class and discriminator value.
func (r *SubTypeRegistry) Register(base, value string, factory SubTypeFactory) {
	if r.entries[base] == nil {
		r.entries[base] = map[string]SubTypeFactory{}
	}
	r.entries[base][value] = factory
}

// Create builds the concrete message selected by value, or nil when unknown.
func (r *SubTypeRegistry) Create(base, value string, data map[string]any) (Message, error) {
	factory := r.entries[base][value]
	if factory == nil {
		return nil, nil
	}
	return factory(data)
}
