// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericEnum.proto

package constant.tsnumeric;

public interface ClaimStatusNames {
  String acceptable = "acceptable";
  String active = "active";
  String claimable = "claimable";
}
