// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericEnum.proto

package constant.tsnumeric;

public interface FooNames {
  String a = "a";
  String b = "b";
  String c = "c";
}
