// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Test5.proto

package test5;

public interface TestNames {
  String DEFAULT = "DEFAULT";
  String OTHER = "OTHER";
}
