// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericDebugEnum.proto

package constant.tsnumericdebug;

import io.github.jinganix.webpb.runtime.enumeration.Enumeration;

public enum Bar implements Enumeration<Integer> {
  x(0),
  y(1),
  z(2);

  private Integer value;

  Bar(Integer value) {
    this.value = value;
  }

  public static Bar fromValue(Integer value) {
    switch (value) {
      case 0:
        return x;
      case 1:
        return y;
      case 2:
        return z;
      default:
        return null;
    }
  }

  @Override
  public Integer getValue() {
    return this.value;
  }
}
