// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericDebugEnum.proto

package constant.tsnumericdebug;

public interface LogLevelNames {
  String info = "info";
  String warn = "warn";
  String error = "error";
}
