// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericDebugEnum.proto

package constant.tsnumericdebug;

import io.github.jinganix.webpb.runtime.enumeration.Enumeration;

public enum LogLevel implements Enumeration<Integer> {
  info(0),
  warn(1),
  error(2);

  private Integer value;

  LogLevel(Integer value) {
    this.value = value;
  }

  public static LogLevel fromValue(Integer value) {
    switch (value) {
      case 0:
        return info;
      case 1:
        return warn;
      case 2:
        return error;
      default:
        return null;
    }
  }

  @Override
  public Integer getValue() {
    return this.value;
  }
}
