// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericDebugEnum.proto

package constant.tsnumericdebug;

public interface LogLevelValues {
  int info = 0;
  int warn = 1;
  int error = 2;
}
