// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// EmptyJavaPackage.proto

import * as Webpb from "webpb";

export interface INoPackageTest {
  foo: number;
}

export class NoPackageTest implements INoPackageTest, Webpb.WebpbMessage {
  foo!: number;

  static CLASS = "NoPackageTest";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: INoPackageTest) {
    Webpb.assign(p, this, []);
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: NoPackageTest.CLASS,
      context: NoPackageTest.CONTEXT,
      method: NoPackageTest.METHOD,
      path: "",
    };
  }

  static create(p?: INoPackageTest): NoPackageTest {
    return new NoPackageTest(p);
  }

  static fromAlias(data?: unknown): NoPackageTest {
    return NoPackageTest.create(data as INoPackageTest);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}

export interface INoPackage {
  foo_1: number;
  bar_1: string;
  test: INoPackageTest;
}

export class NoPackage implements INoPackage, Webpb.WebpbMessage {
  foo_1!: number;
  bar_1!: string;
  test!: INoPackageTest;

  static CLASS = "NoPackage";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: INoPackage) {
    Webpb.assign(p, this, []);
    p?.test && (this.test = NoPackageTest.create(p.test));
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: NoPackage.CLASS,
      context: NoPackage.CONTEXT,
      method: NoPackage.METHOD,
      path: "",
    };
  }

  static create(p?: INoPackage): NoPackage {
    return new NoPackage(p);
  }

  static fromAlias(data?: unknown): NoPackage {
    const p = data as Record<string, unknown>;
    p?.test && (p.test = NoPackageTest.fromAlias(p.test));
    return Object.assign(new NoPackage(), p);
  }

  toWebpbAlias(): unknown {
    return Webpb.toAlias(this, {});
  }
}
