// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// FileJsonIgnore.proto

package webpbpb

const (
	TestClass   = "Test"
	TestMethod  = ""
	TestContext = ""
)

type Test struct {
	Test1 int64 `webpb:"test1" json:"test1"`
}

func NewTest() *Test {
	return &Test{}
}

func (m *Test) WebpbClass() string   { return TestClass }
func (m *Test) WebpbMethod() string  { return TestMethod }
func (m *Test) WebpbContext() string { return TestContext }
func (m *Test) WebpbPath() string    { return "" }
