// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// GetterSetter.proto

package webpbpb

const (
	TestClass   = "Test"
	TestMethod  = ""
	TestContext = ""
)

type Test struct {
	Test1   int32 `webpb:"test1" json:"test1"`
	Test2   bool  `webpb:"test2" json:"test2"`
	IsTest3 bool  `webpb:"isTest3" json:"isTest3"`
}

func NewTest() *Test {
	return &Test{}
}

func (m *Test) WebpbClass() string   { return TestClass }
func (m *Test) WebpbMethod() string  { return TestMethod }
func (m *Test) WebpbContext() string { return TestContext }
func (m *Test) WebpbPath() string    { return "" }
