// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// RepeatedMessageValid.proto

package webpbpb

const (
	ItemClass   = "Item"
	ItemMethod  = ""
	ItemContext = ""
)

type Item struct {
	Message string `webpb:"message" json:"message"`
}

func NewItem() *Item {
	return &Item{}
}

func (m *Item) WebpbClass() string   { return ItemClass }
func (m *Item) WebpbMethod() string  { return ItemMethod }
func (m *Item) WebpbContext() string { return ItemContext }
func (m *Item) WebpbPath() string    { return "" }

const (
	RepeatedMessageValidClass   = "RepeatedMessageValid"
	RepeatedMessageValidMethod  = ""
	RepeatedMessageValidContext = ""
)

type RepeatedMessageValid struct {
	Items []*Item  `webpb:"items" json:"items"`
	Tags  []string `webpb:"tags" json:"tags"`
}

func NewRepeatedMessageValid() *RepeatedMessageValid {
	return &RepeatedMessageValid{}
}

func (m *RepeatedMessageValid) WebpbClass() string   { return RepeatedMessageValidClass }
func (m *RepeatedMessageValid) WebpbMethod() string  { return RepeatedMessageValidMethod }
func (m *RepeatedMessageValid) WebpbContext() string { return RepeatedMessageValidContext }
func (m *RepeatedMessageValid) WebpbPath() string    { return "" }
