// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// RepeatedEnum.proto

package webpbpb

type Status int32

const (
	Status_ACTIVE   Status = 0
	Status_INACTIVE Status = 1
)

var StatusNames = map[Status]string{
	Status_ACTIVE:   "ACTIVE",
	Status_INACTIVE: "INACTIVE",
}

func (x Status) String() string {
	if name, ok := StatusNames[x]; ok {
		return name
	}
	return ""
}

const (
	RepeatedEnumClass   = "RepeatedEnum"
	RepeatedEnumMethod  = ""
	RepeatedEnumContext = ""
)

type RepeatedEnum struct {
	Status       []Status         `webpb:"status" json:"status"`
	StatusByCode map[int32]Status `webpb:"status_by_code" json:"status_by_code"`
}

func NewRepeatedEnum() *RepeatedEnum {
	return &RepeatedEnum{}
}

func (m *RepeatedEnum) WebpbClass() string   { return RepeatedEnumClass }
func (m *RepeatedEnum) WebpbMethod() string  { return RepeatedEnumMethod }
func (m *RepeatedEnum) WebpbContext() string { return RepeatedEnumContext }
func (m *RepeatedEnum) WebpbPath() string    { return "" }
