// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// UtilityPackage.proto

package webpbpb

const (
	Test10Class   = "Test10"
	Test10Method  = ""
	Test10Context = ""
)

type Test10 struct {
	Test1 int32 `webpb:"test1" json:"test1"`
}

func NewTest10() *Test10 {
	return &Test10{}
}

func (m *Test10) WebpbClass() string   { return Test10Class }
func (m *Test10) WebpbMethod() string  { return Test10Method }
func (m *Test10) WebpbContext() string { return Test10Context }
func (m *Test10) WebpbPath() string    { return "" }
