// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsStringValuesEnum.proto

package constant.tsstringvalues;

import io.github.jinganix.webpb.runtime.enumeration.Enumeration;

public enum TokenType implements Enumeration<String> {
  BEARER("Bearer"),
  ACCESS("Access");

  private String value;

  TokenType(String value) {
    this.value = value;
  }

  public static TokenType fromValue(String value) {
    switch (value) {
      case "Bearer":
        return BEARER;
      case "Access":
        return ACCESS;
      default:
        return null;
    }
  }

  @Override
  public String getValue() {
    return this.value;
  }
}
