// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsStringValuesEnum.proto

package constant.tsstringvalues;

public interface TokenTypeNames {
  String BEARER = "BEARER";
  String ACCESS = "ACCESS";
}
