// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericEnum.proto

package constant.tsnumeric;

import io.github.jinganix.webpb.runtime.enumeration.Enumeration;

public enum ClaimStatus implements Enumeration<Integer> {
  acceptable(0),
  active(1),
  claimable(2);

  private Integer value;

  ClaimStatus(Integer value) {
    this.value = value;
  }

  public static ClaimStatus fromValue(Integer value) {
    switch (value) {
      case 0:
        return acceptable;
      case 1:
        return active;
      case 2:
        return claimable;
      default:
        return null;
    }
  }

  @Override
  public Integer getValue() {
    return this.value;
  }
}
