// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericEnum.proto

package constant.tsnumeric;

public interface ClaimStatusValues {
  int acceptable = 0;
  int active = 1;
  int claimable = 2;
}
