// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// MapValueEnum.proto

package webpbpb

type Direction int32

const (
	Direction_asc  Direction = 0
	Direction_desc Direction = 1
)

var DirectionNames = map[Direction]string{
	Direction_asc:  "asc",
	Direction_desc: "desc",
}

func (x Direction) String() string {
	if name, ok := DirectionNames[x]; ok {
		return name
	}
	return ""
}

const (
	MapValueTestPbClass   = "MapValueTestPb"
	MapValueTestPbMethod  = ""
	MapValueTestPbContext = ""
)

type MapValueTestPb struct {
	Sort map[string]Direction `webpb:"sort" json:"sort"`
}

func NewMapValueTestPb() *MapValueTestPb {
	return &MapValueTestPb{}
}

func (m *MapValueTestPb) WebpbClass() string   { return MapValueTestPbClass }
func (m *MapValueTestPb) WebpbMethod() string  { return MapValueTestPbMethod }
func (m *MapValueTestPb) WebpbContext() string { return MapValueTestPbContext }
func (m *MapValueTestPb) WebpbPath() string    { return "" }
