// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// TsNumericJsDts.proto

package webpbpb

type Foo int32

const (
	Foo_a Foo = 0
	Foo_b Foo = 1
	Foo_c Foo = 2
)

var FooNames = map[Foo]string{
	Foo_a: "a",
	Foo_b: "b",
	Foo_c: "c",
}

func (x Foo) String() string {
	if name, ok := FooNames[x]; ok {
		return name
	}
	return ""
}
