// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// WithoutDefaultConst.proto

package webpbpb

type ConstEnum1 int32

const (
	ConstEnum1_DEFAULT ConstEnum1 = 0
)

var ConstEnum1Names = map[ConstEnum1]string{
	ConstEnum1_DEFAULT: "DEFAULT",
}

func (x ConstEnum1) String() string {
	if name, ok := ConstEnum1Names[x]; ok {
		return name
	}
	return ""
}
