// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// PrimitiveTypes.proto

import * as Webpb from "webpb";

export interface IPrimitiveTypes {
  float_field: number;
  double_field: number;
  uint32_field: number;
  uint64_field: number;
  sint32_field: number;
  sint64_field: number;
  fixed32_field: number;
  fixed64_field: number;
  sfixed32_field: number;
  sfixed64_field: number;
  repeated_float: number[];
}

export class PrimitiveTypes implements IPrimitiveTypes, Webpb.WebpbMessage {
  float_field!: number;
  double_field!: number;
  uint32_field!: number;
  uint64_field!: number;
  sint32_field!: number;
  sint64_field!: number;
  fixed32_field!: number;
  fixed64_field!: number;
  sfixed32_field!: number;
  sfixed64_field!: number;
  repeated_float!: number[];
  webpbMeta: () => Webpb.WebpbMeta;

  static CLASS = "PrimitiveTypes";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IPrimitiveTypes) {
    Webpb.assign(p, this, []);
    this.webpbMeta = () =>
      ({
        class: "PrimitiveTypes",
        context: "",
        method: "",
        path: "",
      }) as Webpb.WebpbMeta;
  }

  static create(p?: IPrimitiveTypes): PrimitiveTypes {
    return new PrimitiveTypes(p);
  }

  static fromAlias(data?: unknown): PrimitiveTypes {
    return PrimitiveTypes.create(data as IPrimitiveTypes);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
