// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// RepeatedMessageValid.proto

import * as Webpb from "webpb";

export interface IItem {
  message: string;
}

export class Item implements IItem, Webpb.WebpbMessage {
  message!: string;
  webpbMeta: () => Webpb.WebpbMeta;

  static CLASS = "Item";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IItem) {
    Webpb.assign(p, this, []);
    this.webpbMeta = () =>
      ({
        class: "Item",
        context: "",
        method: "",
        path: "",
      }) as Webpb.WebpbMeta;
  }

  static create(p?: IItem): Item {
    return new Item(p);
  }

  static fromAlias(data?: unknown): Item {
    return Item.create(data as IItem);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}

export interface IRepeatedMessageValid {
  items: IItem[];
  tags: string[];
}

export class RepeatedMessageValid
  implements IRepeatedMessageValid, Webpb.WebpbMessage
{
  items!: IItem[];
  tags!: string[];
  webpbMeta: () => Webpb.WebpbMeta;

  static CLASS = "RepeatedMessageValid";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IRepeatedMessageValid) {
    Webpb.assign(p, this, []);
    p?.items && (this.items = p.items.map((x) => Item.create(x)));
    this.webpbMeta = () =>
      ({
        class: "RepeatedMessageValid",
        context: "",
        method: "",
        path: "",
      }) as Webpb.WebpbMeta;
  }

  static create(p?: IRepeatedMessageValid): RepeatedMessageValid {
    return new RepeatedMessageValid(p);
  }

  static fromAlias(data?: unknown): RepeatedMessageValid {
    const p = data as Record<string, unknown>;
    p?.items &&
      (p.items = (p.items as Webpb.WebpbMessage[]).map((x) =>
        Item.fromAlias(x),
      ));
    return Object.assign(new RepeatedMessageValid(), p);
  }

  toWebpbAlias(): unknown {
    return Webpb.toAlias(this, {});
  }
}
