// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// ConstEnum2.proto

package constant.enum2;

public interface ConstEnum2Names {
  String DEFAULT = "DEFAULT";
}
