// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// HttpMethods.proto

import * as Webpb from "webpb";

export interface IPostRequest {
  id?: number | null;
  body?: string | null;
}

export class PostRequest implements IPostRequest, Webpb.WebpbMessage {
  id?: number | null;
  body?: string | null;

  static CLASS = "PostRequest";
  static CONTEXT = "/api";
  static METHOD = "POST";
  static PATH = "/items/{id}";

  protected constructor(p?: IPostRequest) {
    Webpb.assign(p, this, []);
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: PostRequest.CLASS,
      context: PostRequest.CONTEXT,
      method: PostRequest.METHOD,
      path: `/items/${this.id}`,
    };
  }

  static create(p?: IPostRequest): PostRequest {
    return new PostRequest(p);
  }

  static fromAlias(data?: unknown): PostRequest {
    return PostRequest.create(data as IPostRequest);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}

export interface IPutRequest {
  id?: number | null;
  body?: string | null;
}

export class PutRequest implements IPutRequest, Webpb.WebpbMessage {
  id?: number | null;
  body?: string | null;

  static CLASS = "PutRequest";
  static CONTEXT = "/api";
  static METHOD = "PUT";
  static PATH = "/items/{id}";

  protected constructor(p?: IPutRequest) {
    Webpb.assign(p, this, []);
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: PutRequest.CLASS,
      context: PutRequest.CONTEXT,
      method: PutRequest.METHOD,
      path: `/items/${this.id}`,
    };
  }

  static create(p?: IPutRequest): PutRequest {
    return new PutRequest(p);
  }

  static fromAlias(data?: unknown): PutRequest {
    return PutRequest.create(data as IPutRequest);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}

export interface IDeleteRequest {
  id?: number | null;
}

export class DeleteRequest implements IDeleteRequest, Webpb.WebpbMessage {
  id?: number | null;

  static CLASS = "DeleteRequest";
  static CONTEXT = "/api";
  static METHOD = "DELETE";
  static PATH = "/items/{id}";

  protected constructor(p?: IDeleteRequest) {
    Webpb.assign(p, this, []);
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: DeleteRequest.CLASS,
      context: DeleteRequest.CONTEXT,
      method: DeleteRequest.METHOD,
      path: `/items/${this.id}`,
    };
  }

  static create(p?: IDeleteRequest): DeleteRequest {
    return new DeleteRequest(p);
  }

  static fromAlias(data?: unknown): DeleteRequest {
    return DeleteRequest.create(data as IDeleteRequest);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
