// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// RepeatedFieldTypes.proto

import * as Webpb from "webpb";

export interface IRepeatedFieldTypes {
  as_list: string[];
  as_set: string[];
  as_collection: string[];
}

export class RepeatedFieldTypes
  implements IRepeatedFieldTypes, Webpb.WebpbMessage
{
  as_list!: string[];
  as_set!: string[];
  as_collection!: string[];

  static CLASS = "RepeatedFieldTypes";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IRepeatedFieldTypes) {
    Webpb.assign(p, this, []);
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: RepeatedFieldTypes.CLASS,
      context: RepeatedFieldTypes.CONTEXT,
      method: RepeatedFieldTypes.METHOD,
      path: "",
    };
  }

  static create(p?: IRepeatedFieldTypes): RepeatedFieldTypes {
    return new RepeatedFieldTypes(p);
  }

  static fromAlias(data?: unknown): RepeatedFieldTypes {
    return RepeatedFieldTypes.create(data as IRepeatedFieldTypes);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
