// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// RepeatedEnum.proto

import * as Webpb from "webpb";

export enum Status {
  ACTIVE = 0,
  INACTIVE = 1,
}

export const StatusValues = [Status.ACTIVE, Status.INACTIVE];

export const enum ConstStatus {
  ACTIVE = 0,
  INACTIVE = 1,
}

export const ConstStatusValues = [ConstStatus.ACTIVE, ConstStatus.INACTIVE];

export interface IRepeatedEnum {
  status: Status[];
  status_by_code: Record<number, Status>;
}

export class RepeatedEnum implements IRepeatedEnum, Webpb.WebpbMessage {
  status!: Status[];
  status_by_code!: Record<number, Status>;

  static CLASS = "RepeatedEnum";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IRepeatedEnum) {
    Webpb.assign(p, this, []);
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: RepeatedEnum.CLASS,
      context: RepeatedEnum.CONTEXT,
      method: RepeatedEnum.METHOD,
      path: "",
    };
  }

  static create(p?: IRepeatedEnum): RepeatedEnum {
    return new RepeatedEnum(p);
  }

  static fromAlias(data?: unknown): RepeatedEnum {
    return RepeatedEnum.create(data as IRepeatedEnum);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}

export namespace RepeatedEnum {
  export interface IStatusByCodeEntry {
    key?: number | null;
    value?: Status | null;
  }

  export class StatusByCodeEntry
    implements IStatusByCodeEntry, Webpb.WebpbMessage
  {
    key?: number | null;
    value?: Status | null;

    static CLASS = "StatusByCodeEntry";
    static CONTEXT = "";
    static METHOD = "";
    static PATH = "";

    protected constructor(p?: IStatusByCodeEntry) {
      Webpb.assign(p, this, []);
    }

    webpbMeta(): Webpb.WebpbMeta {
      return {
        class: StatusByCodeEntry.CLASS,
        context: StatusByCodeEntry.CONTEXT,
        method: StatusByCodeEntry.METHOD,
        path: "",
      };
    }

    static create(p?: IStatusByCodeEntry): StatusByCodeEntry {
      return new StatusByCodeEntry(p);
    }

    static fromAlias(data?: unknown): StatusByCodeEntry {
      return StatusByCodeEntry.create(data as IStatusByCodeEntry);
    }

    toWebpbAlias(): unknown {
      return this;
    }
  }
}
