// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// GetterSetter.proto

import * as Webpb from "webpb";

export interface ITest {
  test1?: number | null;
  test2?: boolean | null;
  isTest3?: boolean | null;
}

export class Test implements ITest, Webpb.WebpbMessage {
  test1?: number | null;
  test2?: boolean | null;
  isTest3?: boolean | null;

  static CLASS = "Test";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: ITest) {
    Webpb.assign(p, this, []);
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: Test.CLASS,
      context: Test.CONTEXT,
      method: Test.METHOD,
      path: "",
    };
  }

  static create(p?: ITest): Test {
    return new Test(p);
  }

  static fromAlias(data?: unknown): Test {
    return Test.create(data as ITest);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
