// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// UtilityPackage.proto

import * as Webpb from "webpb";

export interface ITest10 {
  test1?: number | null;
}

export class Test10 implements ITest10, Webpb.WebpbMessage {
  test1?: number | null;

  static CLASS = "Test10";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: ITest10) {
    Webpb.assign(p, this, []);
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: Test10.CLASS,
      context: Test10.CONTEXT,
      method: Test10.METHOD,
      path: "",
    };
  }

  static create(p?: ITest10): Test10 {
    return new Test10(p);
  }

  static fromAlias(data?: unknown): Test10 {
    return Test10.create(data as ITest10);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
