// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// RepeatedMessageValid.proto

package repeated_message_valid;

import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;
import jakarta.validation.constraints.NotNull;

public class Item implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META =
      new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  @NotNull private String message;

  public Item() {}

  public Item(String message) {
    this.message = message;
  }

  public String getMessage() {
    return this.message;
  }

  public Item setMessage(String message) {
    this.message = message;
    return this;
  }
}
