// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Extend.proto

package auto.alias.extend;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;

public class Level2 extends Level3 implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META = new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  @JsonProperty("b")
  private Integer foo_2;

  public Level2() {
  }

  public Level2(Integer foo_2) {
    this.foo_2 = foo_2;
  }

  public Integer getFoo_2() {
    return this.foo_2;
  }

  public Level2 setFoo_2(Integer foo_2) {
    this.foo_2 = foo_2;
    return this;
  }
}
