// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// ImportTest.proto

package main;

import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;

public class ImportTest extends NoPackage implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META = new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private Integer foo_2;

  private String bar_2;

  private NoPackage no_package;

  public ImportTest() {
  }

  public ImportTest(Integer foo_2, String bar_2, NoPackage no_package) {
    this.foo_2 = foo_2;
    this.bar_2 = bar_2;
    this.no_package = no_package;
  }

  public Integer getFoo_2() {
    return this.foo_2;
  }

  public ImportTest setFoo_2(Integer foo_2) {
    this.foo_2 = foo_2;
    return this;
  }

  public String getBar_2() {
    return this.bar_2;
  }

  public ImportTest setBar_2(String bar_2) {
    this.bar_2 = bar_2;
    return this;
  }

  public NoPackage getNo_package() {
    return this.no_package;
  }

  public ImportTest setNo_package(NoPackage no_package) {
    this.no_package = no_package;
    return this;
  }
}
