// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Include2.proto

package webpbpb

const (
	MessageClass   = "Message"
	MessageMethod  = ""
	MessageContext = ""
)

type Message struct {
	Id *int32 `webpb:"id" json:"id"`
}

func NewMessage() *Message {
	return &Message{}
}

func (m *Message) WebpbClass() string   { return MessageClass }
func (m *Message) WebpbMethod() string  { return MessageMethod }
func (m *Message) WebpbContext() string { return MessageContext }
func (m *Message) WebpbPath() string    { return "" }

const (
	Message_NestedClass   = "Nested"
	Message_NestedMethod  = ""
	Message_NestedContext = ""
)

type Message_Nested struct {
	Test1 *int32 `webpb:"test1" json:"test1"`
}

func NewMessage_Nested() *Message_Nested {
	return &Message_Nested{}
}

func (m *Message_Nested) WebpbClass() string   { return Message_NestedClass }
func (m *Message_Nested) WebpbMethod() string  { return Message_NestedMethod }
func (m *Message_Nested) WebpbContext() string { return Message_NestedContext }
func (m *Message_Nested) WebpbPath() string    { return "" }
