// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// RepeatedEnum.proto

package repeated_enum;

import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;
import java.util.List;
import java.util.Map;

public class RepeatedEnum implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META =
      new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private List<Status> status;

  private Map<Integer, Status> status_by_code;

  public RepeatedEnum() {}

  public RepeatedEnum(List<Status> status, Map<Integer, Status> status_by_code) {
    this.status = status;
    this.status_by_code = status_by_code;
  }

  public List<Status> getStatus() {
    return this.status;
  }

  public RepeatedEnum setStatus(List<Status> status) {
    this.status = status;
    return this;
  }

  public Map<Integer, Status> getStatus_by_code() {
    return this.status_by_code;
  }

  public RepeatedEnum setStatus_by_code(Map<Integer, Status> status_by_code) {
    this.status_by_code = status_by_code;
    return this;
  }

  public static class StatusByCodeEntry implements WebpbMessage {

    public static final String WEBPB_METHOD = "";

    public static final String WEBPB_CONTEXT = "";

    public static final String WEBPB_PATH = "";

    public static final WebpbMeta WEBPB_META =
        new WebpbMeta.Builder()
            .method(WEBPB_METHOD)
            .context(WEBPB_CONTEXT)
            .path(WEBPB_PATH)
            .build();

    @Override
    public WebpbMeta webpbMeta() {
      return WEBPB_META;
    }

    private Integer key;

    private Status value;

    public StatusByCodeEntry() {}

    public StatusByCodeEntry(Integer key, Status value) {
      this.key = key;
      this.value = value;
    }

    public Integer getKey() {
      return this.key;
    }

    public StatusByCodeEntry setKey(Integer key) {
      this.key = key;
      return this;
    }

    public Status getValue() {
      return this.value;
    }

    public StatusByCodeEntry setValue(Status value) {
      this.value = value;
      return this;
    }
  }
}
