// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// AnotherEnum.proto

package extend.test.main;

import io.github.jinganix.webpb.runtime.enumeration.Enumeration;

public enum Another implements Enumeration<Integer> {

  a(0);

  private Integer value;

  Another(Integer value) {
    this.value = value;
  }

  public static Another fromValue(Integer value) {
    switch (value) {
    case 0:
      return a;
    default:
      return null;
    }
  }

  @Override
  public Integer getValue() {
    return this.value;
  }
}
