// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// SubTypeSubValue.proto

package webpbpb

import (
	"fmt"
	webpb "github.com/jinganix/webpb/runtime/go"
)

type SubTypeSubValueType int32

const (
	SubTypeSubValueType_subTypeSubValue0 SubTypeSubValueType = 0
	SubTypeSubValueType_subTypeSubValue1 SubTypeSubValueType = 1
	SubTypeSubValueType_subTypeSubValue2 SubTypeSubValueType = 2
)

var SubTypeSubValueTypeNames = map[SubTypeSubValueType]string{
	SubTypeSubValueType_subTypeSubValue0: "subTypeSubValue0",
	SubTypeSubValueType_subTypeSubValue1: "subTypeSubValue1",
	SubTypeSubValueType_subTypeSubValue2: "subTypeSubValue2",
}

func (x SubTypeSubValueType) String() string {
	if name, ok := SubTypeSubValueTypeNames[x]; ok {
		return name
	}
	return ""
}

const (
	SubTypeSubValueStringSuperClass   = "SubTypeSubValueStringSuper"
	SubTypeSubValueStringSuperMethod  = ""
	SubTypeSubValueStringSuperContext = ""
)

type SubTypeSubValueStringSuper struct {
	Type *string `webpb:"type" json:"type"`
}

func NewSubTypeSubValueStringSuper() *SubTypeSubValueStringSuper {
	return &SubTypeSubValueStringSuper{}
}

func (m *SubTypeSubValueStringSuper) WebpbClass() string   { return SubTypeSubValueStringSuperClass }
func (m *SubTypeSubValueStringSuper) WebpbMethod() string  { return SubTypeSubValueStringSuperMethod }
func (m *SubTypeSubValueStringSuper) WebpbContext() string { return SubTypeSubValueStringSuperContext }
func (m *SubTypeSubValueStringSuper) WebpbPath() string    { return "" }

const (
	SubTypeSubValueSuperClass   = "SubTypeSubValueSuper"
	SubTypeSubValueSuperMethod  = ""
	SubTypeSubValueSuperContext = ""
)

type SubTypeSubValueSuper struct {
	Type *SubTypeSubValueType `webpb:"type" json:"type"`
}

func NewSubTypeSubValueSuper() *SubTypeSubValueSuper {
	return &SubTypeSubValueSuper{}
}

func (m *SubTypeSubValueSuper) WebpbClass() string   { return SubTypeSubValueSuperClass }
func (m *SubTypeSubValueSuper) WebpbMethod() string  { return SubTypeSubValueSuperMethod }
func (m *SubTypeSubValueSuper) WebpbContext() string { return SubTypeSubValueSuperContext }
func (m *SubTypeSubValueSuper) WebpbPath() string    { return "" }

const (
	SubTypeSubValue0Class   = "SubTypeSubValue0"
	SubTypeSubValue0Method  = ""
	SubTypeSubValue0Context = ""
)

type SubTypeSubValue0 struct {
	Type  *SubTypeSubValueType `webpb:"type" json:"type"`
	Value *int32               `webpb:"value" json:"value"`
}

func NewSubTypeSubValue0() *SubTypeSubValue0 {
	return &SubTypeSubValue0{}
}

func (m *SubTypeSubValue0) WebpbClass() string   { return SubTypeSubValue0Class }
func (m *SubTypeSubValue0) WebpbMethod() string  { return SubTypeSubValue0Method }
func (m *SubTypeSubValue0) WebpbContext() string { return SubTypeSubValue0Context }
func (m *SubTypeSubValue0) WebpbPath() string    { return "" }

const (
	SubTypeSubValue1Class   = "SubTypeSubValue1"
	SubTypeSubValue1Method  = ""
	SubTypeSubValue1Context = ""
)

type SubTypeSubValue1 struct {
	Type  *SubTypeSubValueType `webpb:"type" json:"type"`
	Value *int32               `webpb:"value" json:"value"`
}

func NewSubTypeSubValue1() *SubTypeSubValue1 {
	return &SubTypeSubValue1{}
}

func (m *SubTypeSubValue1) WebpbClass() string   { return SubTypeSubValue1Class }
func (m *SubTypeSubValue1) WebpbMethod() string  { return SubTypeSubValue1Method }
func (m *SubTypeSubValue1) WebpbContext() string { return SubTypeSubValue1Context }
func (m *SubTypeSubValue1) WebpbPath() string    { return "" }

const (
	SubTypeSubValue2Class   = "SubTypeSubValue2"
	SubTypeSubValue2Method  = ""
	SubTypeSubValue2Context = ""
)

type SubTypeSubValue2 struct {
	Type  *SubTypeSubValueType `webpb:"type" json:"type"`
	Value *int32               `webpb:"value" json:"value"`
}

func NewSubTypeSubValue2() *SubTypeSubValue2 {
	return &SubTypeSubValue2{}
}

func (m *SubTypeSubValue2) WebpbClass() string   { return SubTypeSubValue2Class }
func (m *SubTypeSubValue2) WebpbMethod() string  { return SubTypeSubValue2Method }
func (m *SubTypeSubValue2) WebpbContext() string { return SubTypeSubValue2Context }
func (m *SubTypeSubValue2) WebpbPath() string    { return "" }

const (
	SubTypeSubValue3Class   = "SubTypeSubValue3"
	SubTypeSubValue3Method  = ""
	SubTypeSubValue3Context = ""
)

type SubTypeSubValue3 struct {
	Value *int32 `webpb:"value" json:"value"`
}

func NewSubTypeSubValue3() *SubTypeSubValue3 {
	return &SubTypeSubValue3{}
}

func (m *SubTypeSubValue3) WebpbClass() string   { return SubTypeSubValue3Class }
func (m *SubTypeSubValue3) WebpbMethod() string  { return SubTypeSubValue3Method }
func (m *SubTypeSubValue3) WebpbContext() string { return SubTypeSubValue3Context }
func (m *SubTypeSubValue3) WebpbPath() string    { return "" }

const (
	SubTypeSubValue4Class   = "SubTypeSubValue4"
	SubTypeSubValue4Method  = ""
	SubTypeSubValue4Context = ""
)

type SubTypeSubValue4 struct {
	Type  *SubTypeSubValueType `webpb:"type" json:"type"`
	Value *int32               `webpb:"value" json:"value"`
}

func NewSubTypeSubValue4() *SubTypeSubValue4 {
	return &SubTypeSubValue4{}
}

func (m *SubTypeSubValue4) WebpbClass() string   { return SubTypeSubValue4Class }
func (m *SubTypeSubValue4) WebpbMethod() string  { return SubTypeSubValue4Method }
func (m *SubTypeSubValue4) WebpbContext() string { return SubTypeSubValue4Context }
func (m *SubTypeSubValue4) WebpbPath() string    { return "" }

const (
	SubTypeSubValue5Class   = "SubTypeSubValue5"
	SubTypeSubValue5Method  = ""
	SubTypeSubValue5Context = ""
)

type SubTypeSubValue5 struct {
	Type  *SubTypeSubValueType `webpb:"type" json:"type"`
	Value *int32               `webpb:"value" json:"value"`
}

func NewSubTypeSubValue5() *SubTypeSubValue5 {
	return &SubTypeSubValue5{}
}

func (m *SubTypeSubValue5) WebpbClass() string   { return SubTypeSubValue5Class }
func (m *SubTypeSubValue5) WebpbMethod() string  { return SubTypeSubValue5Method }
func (m *SubTypeSubValue5) WebpbContext() string { return SubTypeSubValue5Context }
func (m *SubTypeSubValue5) WebpbPath() string    { return "" }

const (
	SubTypeSubValue6Class   = "SubTypeSubValue6"
	SubTypeSubValue6Method  = ""
	SubTypeSubValue6Context = ""
)

type SubTypeSubValue6 struct {
	Type  *SubTypeSubValueType `webpb:"type" json:"type"`
	Value *int32               `webpb:"value" json:"value"`
}

func NewSubTypeSubValue6() *SubTypeSubValue6 {
	return &SubTypeSubValue6{}
}

func (m *SubTypeSubValue6) WebpbClass() string   { return SubTypeSubValue6Class }
func (m *SubTypeSubValue6) WebpbMethod() string  { return SubTypeSubValue6Method }
func (m *SubTypeSubValue6) WebpbContext() string { return SubTypeSubValue6Context }
func (m *SubTypeSubValue6) WebpbPath() string    { return "" }

var SubTypeSubValueStringSuperSubTypes = webpb.NewSubTypeRegistry()

func init() {
}

func SubTypeSubValueStringSuperFromAliasAny(data map[string]any) (webpb.Message, error) {
	if message, err := SubTypeSubValueStringSuperSubTypes.Create("SubTypeSubValueStringSuper", fmt.Sprint(data["type"]), data); err != nil || message != nil {
		return message, err
	}
	message := NewSubTypeSubValueStringSuper()
	return message, webpb.Populate(data, message)
}

var SubTypeSubValueSuperSubTypes = webpb.NewSubTypeRegistry()

func init() {
	SubTypeSubValueSuperSubTypes.Register("SubTypeSubValueSuper", "SubTypeSubValueType.subTypeSubValue0", func(data map[string]any) (webpb.Message, error) {
		message := NewSubTypeSubValue1()
		return message, webpb.Populate(data, message)
	})
	SubTypeSubValueSuperSubTypes.Register("SubTypeSubValueSuper", "SubTypeSubValueType.subTypeSubValue1", func(data map[string]any) (webpb.Message, error) {
		message := NewSubTypeSubValue2()
		return message, webpb.Populate(data, message)
	})
	SubTypeSubValueSuperSubTypes.Register("SubTypeSubValueSuper", "SubTypeSubValueType.subTypeSubValue2", func(data map[string]any) (webpb.Message, error) {
		message := NewSubTypeSubValue2()
		return message, webpb.Populate(data, message)
	})
	SubTypeSubValueSuperSubTypes.Register("SubTypeSubValueSuper", "foo", func(data map[string]any) (webpb.Message, error) {
		message := NewSubTypeSubValue4()
		return message, webpb.Populate(data, message)
	})
	SubTypeSubValueSuperSubTypes.Register("SubTypeSubValueSuper", "foo.bar", func(data map[string]any) (webpb.Message, error) {
		message := NewSubTypeSubValue5()
		return message, webpb.Populate(data, message)
	})
	SubTypeSubValueSuperSubTypes.Register("SubTypeSubValueSuper", "AnotherEnum.Another.a", func(data map[string]any) (webpb.Message, error) {
		message := NewSubTypeSubValue6()
		return message, webpb.Populate(data, message)
	})
}

func SubTypeSubValueSuperFromAliasAny(data map[string]any) (webpb.Message, error) {
	if message, err := SubTypeSubValueSuperSubTypes.Create("SubTypeSubValueSuper", fmt.Sprint(data["type"]), data); err != nil || message != nil {
		return message, err
	}
	message := NewSubTypeSubValueSuper()
	return message, webpb.Populate(data, message)
}
