// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// EmptyJavaPackage.proto

package webpbpb

const (
	NoPackageTestClass   = "NoPackageTest"
	NoPackageTestMethod  = ""
	NoPackageTestContext = ""
)

type NoPackageTest struct {
	Foo *int32 `webpb:"foo" json:"foo"`
}

func NewNoPackageTest() *NoPackageTest {
	return &NoPackageTest{}
}

func (m *NoPackageTest) WebpbClass() string   { return NoPackageTestClass }
func (m *NoPackageTest) WebpbMethod() string  { return NoPackageTestMethod }
func (m *NoPackageTest) WebpbContext() string { return NoPackageTestContext }
func (m *NoPackageTest) WebpbPath() string    { return "" }

const (
	NoPackageClass   = "NoPackage"
	NoPackageMethod  = ""
	NoPackageContext = ""
)

type NoPackage struct {
	Foo1 *int32         `webpb:"foo_1" json:"foo_1"`
	Bar1 *string        `webpb:"bar_1" json:"bar_1"`
	Test *NoPackageTest `webpb:"test" json:"test"`
}

func NewNoPackage() *NoPackage {
	return &NoPackage{}
}

func (m *NoPackage) WebpbClass() string   { return NoPackageClass }
func (m *NoPackage) WebpbMethod() string  { return NoPackageMethod }
func (m *NoPackage) WebpbContext() string { return NoPackageContext }
func (m *NoPackage) WebpbPath() string    { return "" }
