// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// AliasSkip.proto

package alias_skip;

import io.github.jinganix.webpb.runtime.WebpbMessage;
import io.github.jinganix.webpb.runtime.WebpbMeta;

public class AliasSkip implements WebpbMessage {

  public static final String WEBPB_METHOD = "";

  public static final String WEBPB_CONTEXT = "";

  public static final String WEBPB_PATH = "";

  public static final WebpbMeta WEBPB_META = new WebpbMeta.Builder().method(WEBPB_METHOD).context(WEBPB_CONTEXT).path(WEBPB_PATH).build();

  @Override
  public WebpbMeta webpbMeta() {
    return WEBPB_META;
  }

  private Integer a;

  private Integer b;

  public AliasSkip() {
  }

  public AliasSkip(Integer a, Integer b) {
    this.a = a;
    this.b = b;
  }

  public Integer getA() {
    return this.a;
  }

  public AliasSkip setA(Integer a) {
    this.a = a;
    return this;
  }

  public Integer getB() {
    return this.b;
  }

  public AliasSkip setB(Integer b) {
    this.b = b;
    return this;
  }
}
