// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// AliasReserve.proto

import * as Webpb from "webpb";
import * as AliasReserveProto from "./AliasReserveProto";

export interface IAliasReserveParent {
  foo_1?: number | null;
}

export class AliasReserveParent
  implements IAliasReserveParent, Webpb.WebpbMessage
{
  foo_1?: number | null;
  webpbMeta: () => Webpb.WebpbMeta;

  static CLASS = "AliasReserveParent";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IAliasReserveParent) {
    Webpb.assign(p, this, []);
    this.webpbMeta = () =>
      ({
        class: "AliasReserveParent",
        context: "",
        method: "",
        path: "",
      }) as Webpb.WebpbMeta;
  }

  static create(p?: IAliasReserveParent): AliasReserveParent {
    return new AliasReserveParent(p);
  }

  static fromAlias(data?: unknown): AliasReserveParent {
    const p = Webpb.toAlias(data, {
      b: "foo_1",
    }) as Record<string, unknown>;
    return Object.assign(new AliasReserveParent(), p);
  }

  toWebpbAlias(): unknown {
    return Webpb.toAlias(this, {
      foo_1: "b",
    });
  }
}

export interface IAliasReserveChild
  extends AliasReserveProto.IAliasReserveParent {
  foo_2?: number | null;
}

export class AliasReserveChild
  extends AliasReserveProto.AliasReserveParent
  implements IAliasReserveChild, Webpb.WebpbMessage
{
  foo_2?: number | null;
  webpbMeta: () => Webpb.WebpbMeta;

  static CLASS = "AliasReserveChild";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IAliasReserveChild) {
    super();
    Webpb.assign(p, this, []);
    this.webpbMeta = () =>
      ({
        class: "AliasReserveChild",
        context: "",
        method: "",
        path: "",
      }) as Webpb.WebpbMeta;
  }

  static create(p?: IAliasReserveChild): AliasReserveChild {
    return new AliasReserveChild(p);
  }

  static fromAlias(data?: unknown): AliasReserveChild {
    const p = Webpb.toAlias(data, {
      b: "foo_1",
      g: "foo_2",
    }) as Record<string, unknown>;
    return Object.assign(new AliasReserveChild(), p);
  }

  toWebpbAlias(): unknown {
    return Webpb.toAlias(this, {
      foo_1: "b",
      foo_2: "g",
    });
  }
}
