// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// AliasReserve.proto

import * as Webpb from "webpb";
import * as AliasReserveProto from "./AliasReserveProto";

export interface IAliasReserveParent {
  foo_1?: number | null;
}

export class AliasReserveParent
  implements IAliasReserveParent, Webpb.WebpbMessage
{
  foo_1?: number | null;

  static CLASS = "AliasReserveParent";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IAliasReserveParent) {
    Webpb.assign(p, this, []);
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: AliasReserveParent.CLASS,
      context: AliasReserveParent.CONTEXT,
      method: AliasReserveParent.METHOD,
      path: "",
    };
  }

  static create(p?: IAliasReserveParent): AliasReserveParent {
    return new AliasReserveParent(p);
  }

  static fromAlias(data?: unknown): AliasReserveParent {
    const p = Webpb.toAlias(data, {
      a: "foo_1",
    }) as Record<string, unknown>;
    return Object.assign(new AliasReserveParent(), p);
  }

  toWebpbAlias(): unknown {
    return Webpb.toAlias(this, {
      foo_1: "a",
    });
  }
}

export interface IAliasReserveChild
  extends AliasReserveProto.IAliasReserveParent {
  foo_2?: number | null;
}

export class AliasReserveChild
  extends AliasReserveProto.AliasReserveParent
  implements IAliasReserveChild, Webpb.WebpbMessage
{
  foo_2?: number | null;

  static CLASS = "AliasReserveChild";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IAliasReserveChild) {
    super();
    Webpb.assign(p, this, []);
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: AliasReserveChild.CLASS,
      context: AliasReserveChild.CONTEXT,
      method: AliasReserveChild.METHOD,
      path: "",
    };
  }

  static create(p?: IAliasReserveChild): AliasReserveChild {
    return new AliasReserveChild(p);
  }

  static fromAlias(data?: unknown): AliasReserveChild {
    const p = Webpb.toAlias(data, {
      a: "foo_1",
      f: "foo_2",
    }) as Record<string, unknown>;
    return Object.assign(new AliasReserveChild(), p);
  }

  toWebpbAlias(): unknown {
    return Webpb.toAlias(this, {
      foo_1: "a",
      foo_2: "f",
    });
  }
}
