// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// FieldLevel.proto

import * as Webpb from "webpb";

export interface ILevel3 {
  test1?: number | null;
}

export class Level3 implements ILevel3, Webpb.WebpbMessage {
  test1?: number | null;

  static CLASS = "Level3";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: ILevel3) {
    Webpb.assign(p, this, []);
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: Level3.CLASS,
      context: Level3.CONTEXT,
      method: Level3.METHOD,
      path: "",
    };
  }

  static create(p?: ILevel3): Level3 {
    return new Level3(p);
  }

  static fromAlias(data?: unknown): Level3 {
    return Level3.create(data as ILevel3);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}

export interface ILevel2 {
  test1?: number | null;
  test2?: ILevel3 | null;
  test3: ILevel3[];
}

export class Level2 implements ILevel2, Webpb.WebpbMessage {
  test1?: number | null;
  test2?: ILevel3 | null;
  test3!: ILevel3[];

  static CLASS = "Level2";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: ILevel2) {
    Webpb.assign(p, this, []);
    p?.test2 && (this.test2 = Level3.create(p.test2));
    p?.test3 && (this.test3 = p.test3.map((x) => Level3.create(x)));
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: Level2.CLASS,
      context: Level2.CONTEXT,
      method: Level2.METHOD,
      path: "",
    };
  }

  static create(p?: ILevel2): Level2 {
    return new Level2(p);
  }

  static fromAlias(data?: unknown): Level2 {
    const p = Webpb.toAlias(data, {
      b: "test2",
    }) as Record<string, unknown>;
    p?.test2 && (p.test2 = Level3.fromAlias(p.test2));
    p?.test3 &&
      (p.test3 = (p.test3 as Webpb.WebpbMessage[]).map((x) =>
        Level3.fromAlias(x),
      ));
    return Object.assign(new Level2(), p);
  }

  toWebpbAlias(): unknown {
    const p = Webpb.toAlias(this, {
      test2: "b",
    }) as Record<string, unknown>;
    p.b && (p.b = (p.b as Webpb.WebpbMessage).toWebpbAlias());
    return p;
  }
}

export interface ILevel1 {
  test1?: number | null;
  test2?: ILevel2 | null;
  test3: ILevel2[];
  test4?: ILevel3 | null;
  test5: Record<number, ILevel3>;
  test6: Record<string, ILevel3>;
}

export class Level1 implements ILevel1, Webpb.WebpbMessage {
  test1?: number | null;
  test2?: ILevel2 | null;
  test3!: ILevel2[];
  test4?: ILevel3 | null;
  test5!: Record<number, ILevel3>;
  test6!: Record<string, ILevel3>;

  static CLASS = "Level1";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: ILevel1) {
    Webpb.assign(p, this, []);
    p?.test2 && (this.test2 = Level2.create(p.test2));
    p?.test3 && (this.test3 = p.test3.map((x) => Level2.create(x)));
    p?.test4 && (this.test4 = Level3.create(p.test4));
    p?.test5 &&
      (this.test5 = Webpb.mapValues(p.test5, (x) => Level3.create(x)));
    p?.test6 &&
      (this.test6 = Webpb.mapValues(p.test6, (x) => Level3.create(x)));
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: Level1.CLASS,
      context: Level1.CONTEXT,
      method: Level1.METHOD,
      path: "",
    };
  }

  static create(p?: ILevel1): Level1 {
    return new Level1(p);
  }

  static fromAlias(data?: unknown): Level1 {
    const p = Webpb.toAlias(data, {
      a: "test1",
      e: "test5",
    }) as Record<string, unknown>;
    p?.test2 && (p.test2 = Level2.fromAlias(p.test2));
    p?.test3 &&
      (p.test3 = (p.test3 as Webpb.WebpbMessage[]).map((x) =>
        Level2.fromAlias(x),
      ));
    p?.test4 && (p.test4 = Level3.fromAlias(p.test4));
    p?.test5 &&
      (p.test5 = Webpb.mapValues(p.test5, (x) => Level3.fromAlias(x)));
    p?.test6 &&
      (p.test6 = Webpb.mapValues(p.test6, (x) => Level3.fromAlias(x)));
    return Object.assign(new Level1(), p);
  }

  toWebpbAlias(): unknown {
    const p = Webpb.toAlias(this, {
      test1: "a",
      test5: "e",
    }) as Record<string, unknown>;
    p.e && (p.e = Webpb.mapValues(p.e, (x) => x.toWebpbAlias()));
    return p;
  }
}
