// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Test.proto

package test;

public interface Test3Names {
  String test3_1 = "test3_1";
  String test3_2 = "test3_2";
  String test3_3 = "test3_3";
}
