// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// Test.proto

package test;

import io.github.jinganix.webpb.runtime.enumeration.Enumeration;
import test.message.InterfaceB;

public enum Test5 implements Enumeration<String>, InterfaceA, InterfaceB {

  test5_1("text1"),
  test5_2("text2"),
  test5_3("test5_3");

  private String value;

  Test5(String value) {
    this.value = value;
  }

  public static Test5 fromValue(String value) {
    switch (value) {
    case "text1":
      return test5_1;
    case "text2":
      return test5_2;
    case "test5_3":
      return test5_3;
    default:
      return null;
    }
  }

  @Override
  public String getValue() {
    return this.value;
  }
}
