// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// AnotherEnum.proto

export enum Another {
  a = 0,
}

export const AnotherValues = [
  Another.a,
];

export const enum ConstAnother {
  a = 0,
}

export const ConstAnotherValues = [
  ConstAnother.a,
];
