// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// AliasSkip.proto

import * as Webpb from "webpb";

export interface IAliasSkip {
  b: number;
  a: number;
}

export class AliasSkip implements IAliasSkip, Webpb.WebpbMessage {
  b!: number;
  a!: number;

  static CLASS = "AliasSkip";
  static CONTEXT = "";
  static METHOD = "";
  static PATH = "";

  protected constructor(p?: IAliasSkip) {
    Webpb.assign(p, this, []);
  }

  webpbMeta(): Webpb.WebpbMeta {
    return {
      class: AliasSkip.CLASS,
      context: AliasSkip.CONTEXT,
      method: AliasSkip.METHOD,
      path: "",
    };
  }

  static create(p?: IAliasSkip): AliasSkip {
    return new AliasSkip(p);
  }

  static fromAlias(data?: unknown): AliasSkip {
    return AliasSkip.create(data as IAliasSkip);
  }

  toWebpbAlias(): unknown {
    return this;
  }
}
