name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 10 * * *' # Once per day at 10am UTC
  workflow_dispatch:

jobs:
  commitlint:
    name: Check Commit Message
    runs-on: ubuntu-latest
    if: "${{ !startsWith(github.event.pull_request.title, 'chore: release') }}"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: package.json
          failOnWarnings: true
  build:
    name: Build
    needs: [commitlint]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [8,11,20]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build with Gradle
        run: ./gradlew clean build
  coveralls:
    name: Update Coveralls
    needs: [build]
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Build with Gradle
        run: ./gradlew clean coverage
      - name: Update Coveralls
        run: ./gradlew coveralls
  publish:
    name: Publish
    needs: [build]
    runs-on: ubuntu-latest
    env:
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
      NEXUS_REPO_PASSWORD: ${{ secrets.NEXUS_REPO_PASSWORD }}
      NEXUS_REPO_USERNAME: ${{ secrets.NEXUS_REPO_USERNAME }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Publish to Nexus
        run: ./gradlew publish
