// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
<#if imports?has_content>

  <#list imports as import>
${import}
  </#list>
</#if>

<#list types as type>
  export type ${type?keep_after_last(".")} = ${type};<#lt>
</#list>

export type ${types_name} =
<#list types as type>
  | ${type?keep_after_last(".")}
</#list>;
