// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb
// ${filename}
<#if imports?has_content>

  <#list imports as import>
${import}
  </#list>
</#if>
<#if dynamicImports?has_content>
  <#list dynamicImports as dynamicImport>
import("./${dynamicImport}FromAlias");
  </#list>
</#if>
<#list messages as message>

${message}
</#list>