// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb

<#list imports as import>
${import}
</#list>

<#list types as type>
  <#list type.sub_values as sub_value>
${base_type}.fromAliases[${sub_value}] = ${type.name?cap_first}.fromAlias;
  </#list>
</#list>
