// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb

export { IBadExtends } from "./BadExtendsProto";
import * as BadExtendsProto from "./BadExtendsProto";

export type BadExtendsFooTypes =
  | BadExtendsProto.IBadExtends
;
