// Code generated by Webpb compiler, do not edit.
// https://github.com/jinganix/webpb

import * as BadExtendsProto from "./BadExtendsProto";

export type IBadExtends = BadExtendsProto.IBadExtends;

export type BadExtendsFooTypes =
  | IBadExtends
;
